// MAIN world 注入腳本：攔截 YouTube 播放器發往 /api/timedtext 的請求（XHR 與 fetch 雙 hook），
// 捕獲其真實響應（含 pot token 驗證的完整 URL + 字幕數據），通過 window.postMessage 橋回 content-script。
//
// 背景：YouTube 2024+ 對 timedtext API 引入 pot（proof-of-origin token）防護，
// content-script isolated world 直接 fetch 無 pot 的 baseUrl 會拿到空響應。
// 本腳本運行在 MAIN world，能 hook 播放器自身的 XMLHttpRequest 與 fetch，
// 直接把播放器已成功請求到的響應複用給字幕管線，繞過 pot 生成。
// 播放器可能用 XHR 或 fetch 發字幕請求（不同頁面/版本不一），故兩者都 hook（M1-43）。
//
// §5.1/R1：宿主方法（XMLHttpRequest.prototype.open/send、window.fetch、window.postMessage、
// addEventListener）一律綁定接收者；hook 內部用 apply 保留實例接收者（brand check）。
// §5.3/R3：不改動任何宿主容器/DOM 節點，僅 hook 原型方法與監聽消息，對頁面零侵入。
// §5.4/R4：臨時監聽器（XHR load）用完自除；fetch 包裝無持久監聽器。
// M1-51：本腳本運行在 MAIN world，無法訪問 chrome.storage——調試日誌開關由
// content-script 通過 CustomEvent 中繼（'ai-trans:set-debug-flags'）。
import { diagLog, setDebugFlags } from '../infrastructure/debug-log';

/** 消息通道常量：content-script 與 MAIN world 之間的事件名。 */
export const TIMEDTEXT_CAPTURE_EVENT = 'ai-trans:timedtext-capture';
/** 消息通道常量：內容腳本向 MAIN world 請求觸發/狀態查詢。 */
export const TIMEDTEXT_REQUEST_EVENT = 'ai-trans:timedtext-request';
/** 消息通道常量（M1-47）：content-script 通知目標字幕語言（isolated world → MAIN world）。 */
export const SET_TARGET_LANG_EVENT = 'ai-trans:set-target-lang';
/** 消息通道常量（M1-51）：content-script 中繼調試日誌開關（isolated world → MAIN world）。 */
export const SET_DEBUG_FLAGS_EVENT = 'ai-trans:set-debug-flags';
/** 消息通道常量（M2-22）：content-script 通知視頻切換（SPA 導航），清空 stale 捕獲並重新驅動字幕模組。 */
export const VIDEO_CHANGED_EVENT = 'ai-trans:video-changed';
/** 消息通道常量（M2-22 第三層）：MAIN world 向 content-script 發送 discovered track info（播放器 API 可訪問但 content script 不能）。 */
export const TRACK_INFO_EVENT = 'ai-trans:track-info';
/** 消息通道常量（M2-31）：content-script 通知攔截器停用（enabled=false 時恢復 YouTube 原生字幕）。 */
export const EXTENSION_DISABLED_EVENT = 'ai-trans:disable';
/** 消息通道常量（M2-31）：content-script 通知攔截器重新啟用。 */
export const EXTENSION_ENABLED_EVENT = 'ai-trans:enable';

/** 發送給 content-script 的捕獲結果。 */
export interface TimedTextCapture {
  /** 播放器請求的完整 timedtext URL（含 pot 等簽名參數）。 */
  url: string;
  /** 響應原始文本（JSON3/XML/srv3）。 */
  responseText: string;
  /** 響應 content-type（證據用途）。 */
  contentType: string;
  /** 捕獲時間戳（供最新優先）。 */
  capturedAt: number;
  /** 該 timedtext 請求所屬的視頻 ID（從 URL `v` 參數提取）；無法判定時為空串。 */
  videoId?: string;
}

/** MAIN world 向 content-script 發送的軌道信息（M2-22 第三層：content script 無法訪問播放器 API 時的 fallback）。 */
export interface CapturedTrackInfo {
  lang: string;
  baseUrl: string;
  isAutoGenerated: boolean;
  videoId: string;
  /** M2-31：偵測到的音頻語言（從 timedtext URL 的 lang 參數提取）。 */
  audioLang?: string;
}

/** 注入標記：防止 content-script 重複注入本腳本（SPA 導航/restart 場景）。 */
const INSTALL_FLAG = '__aiTransTimedtextInterceptorInstalled';

/** M2-31：擴充停用旗標——enabled=false 時設為 true，停止所有字幕抑制邏輯，恢復 YouTube 原生字幕。 */
let interceptorDisabled = false;

/** M2-31：偵測到的音頻語言（從 timedtext URL 的 lang 參數提取，作為 audioLocale 的 fallback）。 */
let detectedAudioLang: string | undefined;

/** 判斷 URL 是否為 timedtext 字幕請求（M1-46：放寬 hostname 限制，只匹配路徑）。 */
function isTimedText(url: string): boolean {
  try {
    const u = new URL(url, globalThis.location?.href ?? url);
    // M1-46：manifest matches 已限定 youtube.com，且 YouTube 歷史上用過多種域名變體
    // （video.google.com、m.youtube.com 等），僅匹配 pathname 含 'timedtext'，
    // 不再限制 hostname（保留 localhost 供 E2E）。
    return u.pathname.includes('timedtext');
  } catch {
    return false;
  }
}

/**
 * 安全讀取 XHR 響應文本（M1-47 硬化 + arraybuffer 支援）。
 * 真實瀏覽器中，若播放器把 `responseType` 設為 'json'/'arraybuffer'/'blob'，
 * 讀 `xhr.responseText` 會拋 `InvalidStateError`（jsdom 不拋，故此 bug 只在真實環境暴露）。
 * 此時改從 `xhr.response` 取值：json → JSON.stringify；arraybuffer → UTF-8 解碼；
 * 字符串 → 原樣；其他（blob/document）→ 空串跳過。
 */
function readXhrResponseText(xhr: XMLHttpRequest): string {
  const responseType = (xhr as unknown as { responseType?: string }).responseType ?? '';
  if (responseType === '' || responseType === 'text') {
    return String((xhr as unknown as { responseText?: string }).responseText ?? '');
  }
  const response = (xhr as unknown as { response?: unknown }).response;
  if (response == null) return '';
  if (typeof response === 'string') return response;
  if (responseType === 'json') {
    try {
      return JSON.stringify(response);
    } catch {
      return '';
    }
  }
  // arraybuffer：YouTube 可能使用 binary 傳輸，解碼為 UTF-8 文本
  if (responseType === 'arraybuffer' && response instanceof ArrayBuffer) {
    try {
      return new TextDecoder('utf-8').decode(new Uint8Array(response));
    } catch {
      return '';
    }
  }
  // blob/document 等二進制或非文本類型：本輪不複用（返回空，emitCapture 會跳過）。
  return '';
}

/** 從 timedtext URL 的 `v` query 參數提取視頻 ID；無則返回空串。 */
function extractVideoId(url: string): string {
  try {
    const u = new URL(url, globalThis.location?.href ?? url);
    return u.searchParams.get('v') ?? '';
  } catch {
    return '';
  }
}

/** 從 timedtext URL 提取軌道信息（M2-22 第四層修復）。 */
function extractTrackInfoFromUrl(url: string): CapturedTrackInfo | null {
  try {
    const u = new URL(url, globalThis.location?.href ?? url);
    const videoId = u.searchParams.get('v');
    if (!videoId) return null;
    const lang = u.searchParams.get('lang') ?? 'und';
    const kind = u.searchParams.get('kind');
    return {
      lang,
      baseUrl: u.href,
      isAutoGenerated: kind === 'asr',
      videoId,
      // M2-31：附加偵測到的音頻語言。
      audioLang: detectedAudioLang,
    };
  } catch {
    return null;
  }
}

/** 捕獲並 postMessage 一份響應（非空才轉發，避免污染最新值）。 */
function emitCapture(
  url: string,
  responseText: string,
  contentType: string,
  location: Location
): void {
  // M2-31：擴充停用時不捕獲，避免抑制 YouTube 原生字幕。
  if (interceptorDisabled) return;
  // M2-31：從 timedtext URL 提取音頻語言（首次非 ASR 軌的 lang 參數）。
  if (!detectedAudioLang) {
    try {
      const u = new URL(url, location?.href ?? url);
      const lang = u.searchParams.get('lang');
      const kind = u.searchParams.get('kind');
      // 只記錄非 ASR 軌的語言（ASR 是自動生成的，可能不是音頻語言）。
      if (lang && kind !== 'asr') {
        detectedAudioLang = lang;
        diagLog('interceptor', 'detected audio language from timedtext URL:', lang);
      }
    } catch {
      // URL 解析失敗，忽略。
    }
  }
  if (!responseText) {
    // M2-24 補充修復十二：空響應通常是 YouTube pot 防護信號（首次無 pot 請求返回空）。
    // 不轉發（避免污染 latest），但排程重驅動播放器重發帶 pot 的請求，而非被動等待。
    emptyResponseCount++;
    Reflect.set(globalThis, '__aiTransTimedtextEmptyResponses', emptyResponseCount);
    diagLog('interceptor', 'emitCapture: empty response, skipping (pot re-drive scheduled)');
    schedulePotRedrive();
    return; // 空響應（無登錄態/無字幕）不轉發，也不更新 lastCapture（重播不發空）。
  }
  captureRequestCount++;
  const capture: TimedTextCapture = {
    url,
    responseText,
    contentType: contentType || 'unknown',
    capturedAt: Date.now(),
    videoId: extractVideoId(url),
  };
  diagLog('interceptor', 'emitCapture: success, captureRequestCount:', captureRequestCount, 'videoId:', capture.videoId);
  // 成功捕獲後取消驗證計時器（不再重試驅動）。
  cancelCaptureVerification();
  // M2-24 補充修復十二：成功捕獲後重置 pot 重驅動，並排程復位抑制原生字幕（避免雙重顯示）。
  resetPotRedrive();
  scheduleSuppressNative();
  // M1-46：更新 lastCapture 供重播，並更新調試輔助全局變量。
  lastCapture = capture;
  Reflect.set(globalThis, '__aiTransTimedtextRequests', captureRequestCount);
  Reflect.set(globalThis, '__aiTransTimedtextLastCapture', capture);
  // 即時 postMessage（新開監聽器的場景直接命中）。
  const postMsg = globalThis.postMessage.bind(globalThis);
  postMsg(
    { __aiTrans: true, type: TIMEDTEXT_CAPTURE_EVENT, payload: capture },
    location.origin
  );
  // M2-22 第四層修復：從捕獲的 URL 提取軌道信息發送給 bridge。
  // 當 DOM stale 且播放器 API 不可用時，getCaptionTracksFromPlayerResponse() 失敗，
  // 但捕獲的 URL 本身就包含完整的軌道信息（videoId、lang、kind）。
  const trackInfo = extractTrackInfoFromUrl(url);
  if (trackInfo) {
    diagLog('interceptor', 'emitCapture: sending trackInfo from URL for videoId:', trackInfo.videoId);
    postMsg(
      { __aiTrans: true, type: TRACK_INFO_EVENT, payload: [trackInfo] },
      location.origin
    );
  }
}

/**
 * M2-22 第三層：發送軌道信息給 content script。
 * content script（isolated world）無法訪問 `movie_player.getOption()`，
 * 當 DOM `ytInitialPlayerResponse` stale 時，fetchTrackList() 返回空。
 * 通過 postMessage 將 MAIN world 發現的軌道信息傳遞給 content script，
 * 讓 FetchCaptionSource 可以使用這些信息作為 fallback。
 */
function emitTrackInfo(tracklist: YtCaptionTrack[]): void {
  const currentVid = extractVideoId(globalThis.location?.href ?? '');
  if (!currentVid) return; // 非 watch 頁不發送
  const tracks: CapturedTrackInfo[] = tracklist.map((t) => ({
    lang: String(t.languageCode ?? 'und'),
    baseUrl: String(t.baseUrl ?? ''),
    isAutoGenerated: Boolean(t.kind === 'asr'),
    videoId: currentVid,
  }));
  diagLog('interceptor', 'emitTrackInfo: sending', tracks.length, 'tracks for videoId:', currentVid);
  const postMsg = globalThis.postMessage.bind(globalThis);
  postMsg(
    { __aiTrans: true, type: TRACK_INFO_EVENT, payload: tracks },
    globalThis.location?.origin ?? '*'
  );
}

/** 最近一次捕獲的 timedtext 響應（M1-46 重播機制）。 */
let lastCapture: TimedTextCapture | null = null;

/** 捕獲計數器（調試輔助）：記錄攔截器命中 timedtext 的請求總數。 */
let captureRequestCount = 0;

/**
 * 啟動重播定時器：周期性 postMessage 最近捕獲，讓晚註冊的監聽器也能收到（M1-46）。
 * 背景：M1-45 把攔截器提前到 document_start（MAIN world），但 bridge 監聽器仍在
 * content-script（document_idle）才註冊——播放器在 document_idle 前發的字幕請求
 * 被捕獲後 postMessage，但**監聽器尚未就位，消息丟失** → waitForCapture(15s) 超時
 * → 回退直接 fetch（無 pot）→ 空 body 永久失敗。重播機制使監聽器最遲 1.5s 內收到。
 * M2-22 第四層修復：同時重播軌道信息，確保 bridge 在 video-changed 清空後仍能收到。
 */
function startReplay(): void {
  const REPLAY_INTERVAL_MS = 1_500;
  setInterval(() => {
    if (!lastCapture) return;
    const postMsg = globalThis.postMessage.bind(globalThis);
    postMsg(
      { __aiTrans: true, type: TIMEDTEXT_CAPTURE_EVENT, payload: lastCapture },
      globalThis.location.origin
    );
    // M2-22 第四層：同時重播軌道信息。
    const trackInfo = extractTrackInfoFromUrl(lastCapture.url);
    if (trackInfo) {
      postMsg(
        { __aiTrans: true, type: TRACK_INFO_EVENT, payload: [trackInfo] },
        globalThis.location.origin
      );
    }
  }, REPLAY_INTERVAL_MS);
}

/** 目標字幕語言（M1-47）：由 content-script 經 SET_TARGET_LANG_EVENT 消息設定。
 *  注意：這是「翻譯目標語言」（如 zh-Hant），用於調試輔助與重驅動觸發信號，
 *  不直接用於選軌（字幕來源語言為視頻原文，見 pickTargetTrack 註釋）。 */
let targetLang: string | null = null;

/** 播放器字幕軌條目（YouTube 未文件化結構，僅取用到的欄位）。 */
interface YtCaptionTrack {
  languageCode?: string;
  languageName?: string;
  kind?: string;
  is_translatable?: boolean;
  vss_id?: string;
  name?: { simpleText?: string } | string;
  /** 字幕軌的 timedtext URL（帶簽名參數）；播放器 API 返回的軌通常包含此字段。 */
  baseUrl?: string;
}

/**
 * 從播放器字幕軌列表挑選要載入的軌（M1-47）。
 * 注意：翻譯「目標語言」（如 zh-Hant）與字幕「來源語言」（視頻原文，常為英文）不同，
 * 故不以翻譯目標匹配軌。偏好人工軌（kind !== 'asr'）以取得質量更佳的原文字幕；
 * M2-34：選擇英文軌道（與策略 selectBestTrack 優先級對齊）。
 * 優先級：英文人工 > 英文自動 > 第一個非 ASR > 第一個。
 * 確保攔截器驅動的軌道與策略選擇的軌道一致，避免語言不匹配導致字幕無法顯示。
 */
function pickTargetTrack(tracklist: YtCaptionTrack[]): YtCaptionTrack {
  // 1. 英文人工字幕
  const enManual = tracklist.find((t) => t.languageCode?.toLowerCase().startsWith('en') && t.kind !== 'asr');
  if (enManual) return enManual;
  // 2. 英文自動字幕
  const enAuto = tracklist.find((t) => t.languageCode?.toLowerCase().startsWith('en') && t.kind === 'asr');
  if (enAuto) return enAuto;
  // 3. 第一個非 ASR 軌道
  const manual = tracklist.find((t) => t.kind !== 'asr');
  return manual ?? tracklist[0];
}

/** 標記字幕模組驅動是否已成功（避免重試定時器無限跑）。 */
let captionModuleDriven = false;

/** 捕獲驗證計時器（setOption 成功後啟動，超時未捕獲則重試）。 */
let captureVerifyTimer: ReturnType<typeof setTimeout> | null = null;
/** 捕獲驗證已重試次數（限制最多 3 次重試，避免無限循環）。 */
let captureVerifyRetries = 0;
const MAX_CAPTURE_VERIFY_RETRIES = 3;
const CAPTURE_VERIFY_TIMEOUT_MS = 8_000;

/** 啟動捕獲驗證：setOption 成功後 8 秒內若未捕獲任何 timedtext 響應，則重試驅動。 */
function startCaptureVerification(): void {
  if (captureVerifyTimer !== null) {
    clearTimeout(captureVerifyTimer);
  }
  captureVerifyTimer = setTimeout(() => {
    captureVerifyTimer = null;
    // 若 8 秒內仍未捕獲（lastCapture 為 null 或 videoId 不匹配），則重試驅動。
    const currentVid = extractVideoId(globalThis.location?.href ?? '');
    const hasValidCapture = lastCapture && (!currentVid || lastCapture.videoId === currentVid);
    if (!hasValidCapture && captureVerifyRetries < MAX_CAPTURE_VERIFY_RETRIES) {
      captureVerifyRetries++;
      diagLog('interceptor', 'capture verification timeout, retry', captureVerifyRetries, '/', MAX_CAPTURE_VERIFY_RETRIES);
      captionModuleDriven = false;
      ensureCaptionModuleLoaded();
    } else if (captureVerifyRetries >= MAX_CAPTURE_VERIFY_RETRIES) {
      diagLog('interceptor', 'capture verification exhausted after', MAX_CAPTURE_VERIFY_RETRIES, 'retries');
    }
  }, CAPTURE_VERIFY_TIMEOUT_MS);
}

/** 取消捕獲驗證計時器（成功捕獲或視頻切換時調用）。 */
function cancelCaptureVerification(): void {
  if (captureVerifyTimer !== null) {
    clearTimeout(captureVerifyTimer);
    captureVerifyTimer = null;
  }
  captureVerifyRetries = 0;
}

/**
 * 從 DOM 中的 ytInitialPlayerResponse 解析字幕軌列表（M2-18 修復 + M2-22 videoId 驗證）。
 * 
 * 背景：YouTube 播放器 API `getOption('captions', 'tracklist')` 在某些情況下
 * 持續返回空陣列（即使視頻有字幕），導致字幕驅動失敗。本函式直接從頁面內嵌的
 * `ytInitialPlayerResponse` JSON 提取字幕軌信息，繞過播放器 API。
 * 
 * M2-22：YouTube SPA 導航後 `ytInitialPlayerResponse` 不會更新，仍包含舊視頻的字幕數據。
 * 新增 videoId 驗證：比對 player response 的 videoId 與當前 URL 的 v 參數，
 * 不匹配時返回 undefined，讓調用方 fallback 到播放器 API（`getOption('captions', 'tracklist')`）。
 * 
 * @returns 字幕軌列表；解析失敗、無字幕、或 videoId 不匹配時返回 undefined。
 */
function getCaptionTracksFromPlayerResponse(): YtCaptionTrack[] | undefined {
  // 掃描所有內聯腳本，尋找 ytInitialPlayerResponse 賦值。
  // YouTube 頁面中該腳本通常形如 `var ytInitialPlayerResponse = {...};`
  // 或純 JSON（某些頁面/版本）。
  const scripts = document.querySelectorAll('script:not([src])');
  for (const el of Array.from(scripts)) {
    const text = el.textContent ?? '';
    if (!text.includes('ytInitialPlayerResponse')) continue;
    
    // 嘗試提取 JSON 對象。
    let jsonStr: string | undefined;
    
    // 形式 1: `var ytInitialPlayerResponse = {...};`（JavaScript 賦值）
    const assignMatch = /ytInitialPlayerResponse\s*=\s*(\{[\s\S]*?\})\s*;/.exec(text);
    if (assignMatch) {
      jsonStr = assignMatch[1];
    } else if (text.trim().startsWith('{')) {
      // 形式 2: 純 JSON（script#ytInitialPlayerResponse 可能只含 JSON）
      jsonStr = text.trim();
    }
    
    if (!jsonStr) continue;
    
    try {
      const data = JSON.parse(jsonStr);
      const tracks = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
      if (!Array.isArray(tracks)) continue;
      // M2-22：驗證 videoId——SPA 導航後 ytInitialPlayerResponse 不會更新，
      // 比對 player response 的 videoId 與當前 URL 的 v 參數，不匹配時視為 stale。
      const currentVid = extractVideoId(globalThis.location?.href ?? '');
      const playerVid = data?.videoDetails?.videoId ?? '';
      // M2-22 補充：currentVid 為空（非 watch 頁）時也跳過——無視頻可驅動，
      // 避免 stale DOM 數據被當作有效數據使用。
      if (!currentVid) {
        diagLog('interceptor', 'getCaptionTracksFromPlayerResponse: not on watch page (no videoId), skipping');
        return undefined;
      }
      if (playerVid && currentVid !== playerVid) {
        diagLog('interceptor', 'getCaptionTracksFromPlayerResponse: videoId mismatch, current:', currentVid, 'player:', playerVid, '- stale data');
        return undefined;
      }
      return tracks as YtCaptionTrack[];
    } catch {
      // JSON 解析失敗，繼續嘗試下一個腳本。
    }
  }
  return undefined;
}

/**
 * 主動驅動播放器字幕模組發出 timedtext 請求（M1-47 核心修復 + M2-18 增強）。
 *
 * 背景：真實環境中若用戶未開啟字幕（CC 關閉），播放器**根本不發** timedtext 請求，
 * 攔截器永遠捕獲不到帶 pot 的 URL → waitForCapture 超時 → 回退直接 fetch（無 pot）
 * → YouTube 返回 HTML 登錄頁（empty body）→ 解析失敗。M1-46 的重播只能重發「已捕獲」
 * 的響應，捕獲不到時無濟於事。此函式透過播放器 API 主動載入字幕模組並選軌，
 * 逼播放器自己發帶 pot 的請求，供攔截器捕獲；隨後復位抑制原生字幕顯示。
 *
 * M2-18 增強：`getOption('captions', 'tracklist')` 在某些情況下持續返回空陣列
 * （即使視頻有字幕）。新增 fallback：直接從 DOM 中的 `ytInitialPlayerResponse` 解析
 * 字幕軌信息，繞過播放器 API。
 *
 * 播放器 API（loadModule/getOption/setOption）未文件化且版本多變，全程 try/catch，
 * 失敗不致命（僅回退到原捕獲路徑）。
 */

/** 播放器字幕 API 的最小接口（未文件化，取用到的欄位；全程 try/catch 容錯）。 */
interface CaptionPlayer {
  loadModule?: (m: string) => void;
  getOption?: (m: string, k: string) => unknown;
  setOption?: (m: string, k: string, v: unknown) => void;
}

/** 取播放器元素（字幕模組驅動 / pot 重驅動 / 原生字幕抑制共用）。 */
function getCaptionPlayer(): CaptionPlayer | null {
  return document.getElementById('movie_player') as CaptionPlayer | null;
}

// ── M2-24 補充修復十二：空響應（pot 防護）重驅動 ──
// 真實環境實測：播放器先發無 pot 的 timedtext 請求 → YouTube 返回空 body（length:0,
// text/html）→ 攔截器 skip；播放器**稍後**才內部用 pot 重試。舊實作固定 3 秒復位
// `setOption('captions','track',{})` 可能打斷尚未完成的 pot 重試鏈 → 播放器不再發
// 第二次請求 → waitForCapture(15s) 超時 → 直接 fetch（無 pot）空 body → native 全鏈失敗。
// 修復：空響應視為「需要 pot」的信號，排程重驅動（切換軌 off→on）逼播放器重發帶 pot
// 的請求；復位改為「成功捕獲後抑制原生字幕」+ 10 秒截止，不再用固定 3 秒冒險打斷重試。
const POT_REDRIVE_DELAY_MS = 2_000;
const MAX_POT_REDRIVE_ATTEMPTS = 6;
/** 空響應累計計數（調試輔助：pot 防護命中次數）。 */
let emptyResponseCount = 0;
/** XHR 請求被中止的累計計數（調試輔助：播放器中止請求次數）。 */
let xhrAbortCount = 0;
/** XHR 請求錯誤的累計計數（調試輔助：網絡錯誤次數）。 */
let xhrErrorCount = 0;
/** pot 重驅動已執行的嘗試次數。 */
let potRedriveAttempts = 0;
let potRedriveTimer: ReturnType<typeof setTimeout> | null = null;
/** 捕獲成功後的復位計時器（抑制原生字幕）。 */
let suppressNativeTimer: ReturnType<typeof setTimeout> | null = null;
/** 捕獲始終失敗時的 10 秒截止復位計時器。 */
let suppressDeadlineTimer: ReturnType<typeof setTimeout> | null = null;

/**
 * 排程一次 pot 重驅動（已在途不疊加；達上限停止）。
 * 由 emitCapture 的空響應分支觸發。
 */
function schedulePotRedrive(): void {
  // M2-31：擴充停用時不排程重驅動。
  if (interceptorDisabled) return;
  if (potRedriveTimer !== null) return; // 已有排程，避免疊加。
  if (potRedriveAttempts >= MAX_POT_REDRIVE_ATTEMPTS) {
    diagLog('interceptor', 'pot re-drive exhausted after', potRedriveAttempts, 'attempts');
    return;
  }
  potRedriveAttempts += 1;
  Reflect.set(globalThis, '__aiTransPotRedriveAttempts', potRedriveAttempts);
  diagLog('interceptor', 'pot re-drive scheduled, attempt:', potRedriveAttempts);
  potRedriveTimer = setTimeout(() => {
    potRedriveTimer = null;
    redrivePlayerCaptions();
  }, POT_REDRIVE_DELAY_MS);
}

/** 切換字幕軌 off→on，強制播放器重新拉取 timedtext（YouTube 對重複 setOption 可能 no-op）。 */
function redrivePlayerCaptions(): void {
  diagLog('interceptor', 'pot re-drive executing, attempt:', potRedriveAttempts);
  const player = getCaptionPlayer();
  if (!player || typeof player.setOption !== 'function') {
    // 播放器暫缺/未就緒：延後再試（仍受 MAX_POT_REDRIVE_ATTEMPTS 上限約束）。
    schedulePotRedrive();
    return;
  }
  captionModuleDriven = false;
  try {
    player.setOption('captions', 'track', {});
  } catch {
    /* 復位失敗無害 */
  }
  // 延遲一小段再重新選軌，確保播放器感知軌切換而重發請求。
  setTimeout(() => {
    try {
      ensureCaptionModuleLoaded();
    } catch {
      /* 重驅動失敗不致命：原有捕獲/重播路徑仍在。 */
    }
  }, 150);
}

/** 重置重驅動計數並清除相關計時器（成功捕獲 / 視頻切換時調用）。 */
function resetPotRedrive(): void {
  potRedriveAttempts = 0;
  Reflect.set(globalThis, '__aiTransPotRedriveAttempts', 0);
  if (potRedriveTimer !== null) {
    clearTimeout(potRedriveTimer);
    potRedriveTimer = null;
  }
  if (suppressNativeTimer !== null) {
    clearTimeout(suppressNativeTimer);
    suppressNativeTimer = null;
  }
  if (suppressDeadlineTimer !== null) {
    clearTimeout(suppressDeadlineTimer);
    suppressDeadlineTimer = null;
  }
}

/** 捕獲成功後復位字幕軌（抑制原生字幕與覆蓋層重複），捕獲數據已到手，可安全隱藏。 */
function scheduleSuppressNative(): void {
  // M2-31：擴充停用時不抑制原生字幕。
  if (interceptorDisabled) return;
  if (suppressNativeTimer !== null) return;
  suppressNativeTimer = setTimeout(() => {
    suppressNativeTimer = null;
    const player = getCaptionPlayer();
    if (!player || typeof player.setOption !== 'function') return;
    try {
      player.setOption('captions', 'track', {});
      diagLog('interceptor', 'Caption track reset after successful capture to suppress native rendering');
    } catch {
      /* 復位失敗無害：原生字幕可能短暫顯示，不影響已捕獲的字幕。 */
    }
  }, 800);
}

/** 捕獲始終失敗時的截止復位（避免原生字幕永久顯示）；成功捕獲會由 resetPotRedrive 取消。 */
function scheduleSuppressDeadline(player: CaptionPlayer): void {
  // M2-31：擴充停用時不抑制原生字幕。
  if (interceptorDisabled) return;
  if (suppressDeadlineTimer !== null) return;
  suppressDeadlineTimer = setTimeout(() => {
    suppressDeadlineTimer = null;
    try {
      player.setOption!('captions', 'track', {});
      diagLog('interceptor', 'Caption track reset (10s deadline) to suppress native rendering');
    } catch {
      /* 復位失敗無害 */
    }
  }, 10_000);
}

function ensureCaptionModuleLoaded(): void {
  // M2-31：擴充停用時不驅動字幕模組。
  if (interceptorDisabled) return;
  if (captionModuleDriven) return;
  // M2-22 修復：若 lastCapture 已有當前視頻的數據，表示播放器已自行發出正確的 timedtext 請求，
  // 無需再驅動字幕模組（避免使用 stale DOM 軌列表驅動播放器請求舊視頻字幕）。
  if (lastCapture) {
    const captureVid = lastCapture.videoId ?? '';
    const currentVid = extractVideoId(globalThis.location?.href ?? '');
    if (currentVid && captureVid === currentVid) {
      diagLog('interceptor', 'lastCapture already has current video data (videoId:', currentVid, '), skipping caption module drive');
      captionModuleDriven = true;
      return;
    }
  }
  const player = getCaptionPlayer();

  // 診斷日誌
  if (!player) {
    diagLog('interceptor', 'Player element not found');
    return;
  }
  if (typeof player.loadModule !== 'function' || typeof player.setOption !== 'function') {
    diagLog('interceptor', 'Player API not available');
    return; // 播放器未就緒/API 未暴露：由重試定時器稍後再試。
  }
  
  try {
    player.loadModule('captions');
  } catch {
    // 載入失敗（可能已載入）：繼續嘗試讀軌列表。
  }
  
  // 獲取字幕軌列表：優先從 DOM 解析（M2-18），fallback 到播放器 API。
  let tracklist: YtCaptionTrack[] | undefined;
  let source = 'unknown';
  
  // 優先從 ytInitialPlayerResponse 解析（繞過播放器 API 可能返回空的問題）。
  const domTracks = getCaptionTracksFromPlayerResponse();
  if (domTracks && domTracks.length > 0) {
    tracklist = domTracks;
    source = 'ytInitialPlayerResponse (DOM)';
    diagLog('interceptor', 'Got tracks from ytInitialPlayerResponse:', domTracks.length, 'tracks');
  } else if (typeof player.getOption === 'function') {
    // Fallback: 播放器 API。
    try {
      const raw = player.getOption('captions', 'tracklist');
      diagLog('interceptor', 'getOption tracklist:', raw, 'isArray:', Array.isArray(raw));
      if (Array.isArray(raw) && raw.length > 0) {
        tracklist = raw as YtCaptionTrack[];
        source = 'player.getOption';
      }
    } catch (err) {
      diagLog('interceptor', 'getOption error:', err);
    }
  }
  
  if (!tracklist || tracklist.length === 0) {
    diagLog('interceptor', 'No caption tracks available from DOM or getOption, trying synthetic track');
    // M2-22 第六層：SPA 導航後 DOM stale + getOption 返回 []，但播放器可能內部已有軌道數據。
    // 嘗試用 URL 的 videoId 構造合成軌道驅動播放器，讓播放器自己解析正確的 timedtext URL（含 pot）。
    const currentVid = extractVideoId(globalThis.location?.href ?? '');
    if (currentVid) {
      const syntheticTrack: YtCaptionTrack = {
        languageCode: 'en',
        baseUrl: `https://www.youtube.com/api/timedtext?v=${currentVid}&lang=en&fmt=json3`,
      };
      try {
        player.setOption('captions', 'track', syntheticTrack);
        captionModuleDriven = true;
        diagLog('interceptor', 'Caption module driven with synthetic track for videoId:', currentVid);
        // 捕獲失敗時 10 秒截止復位（M2-24 補充修復十二：不再用固定 3 秒打斷 pot 重試）。
        scheduleSuppressDeadline(player);
        return;
      } catch (err) {
        diagLog('interceptor', 'setOption with synthetic track failed:', err);
      }
    }
    diagLog('interceptor', 'No caption tracks available (video may have no captions)');
    // 無字幕軌：可能真無字幕，或軌列表尚未就緒。標記調試碼，讓重試繼續（真無字幕時無害）。
    Reflect.set(globalThis, '__aiTransCaptionTracks', 0);
    return;
  }
  
  diagLog('interceptor', 'Found', tracklist.length, 'caption tracks from', source);
  Reflect.set(globalThis, '__aiTransCaptionTracks', tracklist.length);
  // M2-22 第三層：發送軌道信息給 content script（content script 無法訪問播放器 API，
  // 當 DOM stale 時需要這些信息來構建字幕軌列表）。
  emitTrackInfo(tracklist);
  
  // 增強診斷 + 異常捕獲：包裹 pickTargetTrack 在 try-catch 中，避免未捕獲異常導致函數提前退出。
  let track: YtCaptionTrack;
  try {
    track = pickTargetTrack(tracklist);
    diagLog('interceptor', 'pickTargetTrack result:', JSON.stringify({
      languageCode: track.languageCode,
      baseUrl: track.baseUrl?.substring(0, 80),
      kind: track.kind,
      hasBaseUrl: Boolean(track.baseUrl),
    }));
  } catch (err) {
    diagLog('interceptor', 'pickTargetTrack error:', err);
    return;
  }
  
  try {
    // 選軌 → 播放器發帶 pot 的 timedtext 請求（被 XHR/fetch hook 捕獲）。
    diagLog('interceptor', 'Calling player.setOption...');
    player.setOption('captions', 'track', track);
    captionModuleDriven = true;
    diagLog('interceptor', 'Caption module driven successfully, selected track:', track);
    // 啟動捕獲驗證：8 秒內若未捕獲任何 timedtext 響應，則重試驅動（處理廣告期間播放器不就緒的情況）。
    startCaptureVerification();
    // M2-24 補充修復十二：不再用固定 3 秒復位（可能打斷播放器尚未完成的 pot 重試），
    // 改為「成功捕獲後抑制原生字幕」+ 10 秒截止復位。原生字幕可能短暫顯示，
    // 但捕獲成功後（scheduleSuppressNative）即被隱藏，可接受。
    scheduleSuppressDeadline(player);
  } catch (err) {
    diagLog('interceptor', 'setOption error:', err);
    diagLog('interceptor', 'setOption error stack:', err instanceof Error ? err.stack : 'no stack');
    // 選軌失敗：不標記成功，重試定時器會再試。
  }
}

/** 啟動字幕模組驅動重試（M1-47）：播放器異步就緒，周期重試直到成功。 */
function startCaptionModuleDriver(): void {
  const RETRY_INTERVAL_MS = 1_000;
  const MAX_RETRIES = 60; // 最多 60 秒等播放器就緒（YouTube 播放器加載可能較慢）
  let attempts = 0;
  const timer = setInterval(() => {
    attempts += 1;
    ensureCaptionModuleLoaded();
    if (captionModuleDriven || attempts >= MAX_RETRIES) {
      clearInterval(timer);
    }
  }, RETRY_INTERVAL_MS);
}

/** SPA 換視頻時重置驅動狀態並重新觸發（M1-47）。 */
function resetAndRedriveCaptionModule(): void {
  // M2-31：擴充停用時不重新驅動。
  if (interceptorDisabled) return;
  // M2-24 補充修復十二：重置 pot 重驅動計數並清除排程（視頻切換/熱重啟時重新開始）。
  resetPotRedrive();
  // 重置捕獲驗證計數器（視頻切換/重啟時重新開始）。
  cancelCaptureVerification();
  captionModuleDriven = false;
  // 立即嘗試一次（處理播放器已就緒的情況）
  ensureCaptionModuleLoaded();
  // 如果未成功，啟動定時器重試（處理播放器尚未就緒的情況）
  if (!captionModuleDriven) {
    startCaptionModuleDriver();
  }
}

function install(): void {
  if (Reflect.get(globalThis, INSTALL_FLAG)) return;
  Reflect.set(globalThis, INSTALL_FLAG, true);
  // M1-46：啟動重播定時器（周期性重發最近捕獲）。
  startReplay();
  // M1-47：接收 content-script 的目標語言，並啟動字幕模組主動驅動。
  // 使用 CustomEvent 替代 postMessage，避免 isolated world 與 MAIN world 之間的通信問題。
  const onSetTargetLang = (ev: Event): void => {
    const detail = (ev as CustomEvent).detail as { targetLang?: string } | undefined;
    targetLang = typeof detail?.targetLang === 'string' ? detail.targetLang : null;
    // 調試輔助：暴露目標語言，供真實環境確認消息通道已通。
    Reflect.set(globalThis, '__aiTransTargetLang', targetLang);
    diagLog('interceptor', 'Received set-target-lang message, targetLang:', targetLang);
    // 收到語言後（重）啟動驅動：涵蓋首次啟動與 SPA 換視頻後 restart 重發。
    resetAndRedriveCaptionModule();
  };
  document.addEventListener('ai-trans:set-target-lang', onSetTargetLang);
  // M1-51：接收 content-script 中繼的調試日誌開關（MAIN world 無法訪問 chrome.storage，
  // 只能靠 CustomEvent 同步；content-script 每次 start/restart 都會重發）。
  const onSetDebugFlags = (ev: Event): void => {
    const detail = (ev as CustomEvent).detail as { flags?: Record<string, boolean> } | undefined;
    setDebugFlags(detail?.flags);
    diagLog('interceptor', 'debug flags updated:', detail?.flags);
  };
  document.addEventListener(SET_DEBUG_FLAGS_EVENT, onSetDebugFlags);
  // M2-22：接收視頻切換通知（SPA 導航），清空 stale 捕獲並重新驅動字幕模組。
  // 背景：YouTube SPA 導航後 `ytInitialPlayerResponse` 不會更新，攔截器的 `lastCapture`
  // 仍保留舊視頻的 timedtext 響應，重播機制會持續發送給 bridge，導致字幕管線複用舊字幕。
  const onVideoChanged = (): void => {
    diagLog('interceptor', 'video-changed event received, clearing lastCapture and resetting captionModuleDriven');
    lastCapture = null;
    // M2-31：重置偵測到的音頻語言（新視頻可能有不同音頻語言）。
    detectedAudioLang = undefined;
    // 同步清空調試輔助全局變量（與 emitCapture 中的設置對應）。
    Reflect.set(globalThis, '__aiTransTimedtextLastCapture', null);
    // 重置捕獲驗證計數器（視頻切換時重新開始）。
    cancelCaptureVerification();
    captionModuleDriven = false;
    resetAndRedriveCaptionModule();
  };
  document.addEventListener(VIDEO_CHANGED_EVENT, onVideoChanged);
  // M2-31：接收擴充停用/啟用通知——enabled=false 時停止所有字幕抑制邏輯，恢復 YouTube 原生字幕。
  const onExtensionDisabled = (): void => {
    interceptorDisabled = true;
    diagLog('interceptor', 'extension disabled, stopping all caption suppression');
    // 清除所有抑制/重驅動定時器。
    if (suppressNativeTimer !== null) {
      clearTimeout(suppressNativeTimer);
      suppressNativeTimer = null;
    }
    if (suppressDeadlineTimer !== null) {
      clearTimeout(suppressDeadlineTimer);
      suppressDeadlineTimer = null;
    }
    if (potRedriveTimer !== null) {
      clearTimeout(potRedriveTimer);
      potRedriveTimer = null;
    }
    // 標記驅動完成，阻止 startCaptionModuleDriver 繼續重試。
    captionModuleDriven = true;
  };
  document.addEventListener(EXTENSION_DISABLED_EVENT, onExtensionDisabled);
  const onExtensionEnabled = (): void => {
    interceptorDisabled = false;
    diagLog('interceptor', 'extension enabled, resuming caption capture');
    captionModuleDriven = false;
    resetAndRedriveCaptionModule();
  };
  document.addEventListener(EXTENSION_ENABLED_EVENT, onExtensionEnabled);
  // 即使未收到語言消息也啟動一次驅動（用第一/人工軌），避免消息時序問題導致完全不驅動。
  startCaptionModuleDriver();
  // 調試輔助（M1-27 真實環境驗證）：暴露計數器與最近捕獲對象到 window。
  Reflect.set(globalThis, '__aiTransTimedtextRequests', 0);
  Reflect.set(globalThis, '__aiTransTimedtextLastCapture', null);
  // M2-24 補充修復十二：暴露 pot 重驅動相關計數（真實環境分流「空響應有無觸發重驅動」）。
  Reflect.set(globalThis, '__aiTransTimedtextEmptyResponses', 0);
  Reflect.set(globalThis, '__aiTransPotRedriveAttempts', 0);

  // ── XHR hook（播放器常用路徑）──
  const origOpen = XMLHttpRequest.prototype.open;
  const origSend = XMLHttpRequest.prototype.send;

  XMLHttpRequest.prototype.open = function (
    method: string,
    url: string | URL,
    async?: boolean,
    username?: string | null,
    password?: string | null
  ): void {
    const urlStr = typeof url === 'string' ? url : url.href;
    if (isTimedText(urlStr)) {
      diagLog('interceptor', 'XHR timedtext request detected:', urlStr);
      (this as unknown as { __aiTransUrl?: string }).__aiTransUrl = urlStr;
    }
    return origOpen.apply(this, [method, url, async ?? true, username, password]);
  };

  XMLHttpRequest.prototype.send = function (
    ...args: [body?: Document | XMLHttpRequestBodyInit | null]
  ): void {
    const urlStr = (this as unknown as { __aiTransUrl?: string }).__aiTransUrl;
    if (urlStr) {
      diagLog('interceptor', 'XHR timedtext request sending:', urlStr);
      // R4：監聽器在請求完成/中止/錯誤後移除自身，不產生累積洩漏。
      const cleanup = (): void => {
        this.removeEventListener('load', onLoad);
        this.removeEventListener('abort', onAbort);
        this.removeEventListener('error', onError);
      };
      const onLoad = (): void => {
        cleanup();
        try {
          const responseType = (this as unknown as { responseType?: string }).responseType ?? '';
          const status = (this as unknown as { status?: number }).status ?? 0;
          diagLog('interceptor', 'XHR timedtext onLoad: status:', status, 'responseType:', responseType);
          const responseText = readXhrResponseText(this);
          const contentType =
            (this as unknown as { getResponseHeader?: (h: string) => string | null })
              .getResponseHeader?.('content-type') ?? 'unknown';
          diagLog('interceptor', 'XHR timedtext response received, length:', responseText.length, 'content-type:', contentType);
          emitCapture(urlStr, responseText, contentType, globalThis.location);
        } catch {
          // §5.7：外部響應解析失敗不允許冒泡破壞播放器——吞掉（捕獲失敗僅意味著本輪不複用）。
        }
      };
      const onAbort = (): void => {
        cleanup();
        xhrAbortCount++;
        diagLog('interceptor', 'XHR timedtext request ABORTED:', urlStr, 'total aborts:', xhrAbortCount);
        // 中止視為「需要重試」信號，觸發 pot re-drive
        schedulePotRedrive();
      };
      const onError = (): void => {
        cleanup();
        xhrErrorCount++;
        diagLog('interceptor', 'XHR timedtext request ERROR:', urlStr, 'total errors:', xhrErrorCount);
        // 錯誤視為「需要重試」信號，觸發 pot re-drive
        schedulePotRedrive();
      };
      this.addEventListener('load', onLoad);
      this.addEventListener('abort', onAbort);
      this.addEventListener('error', onError);
    }
    return origSend.apply(this, args);
  };

  // ── fetch hook（播放器變體路徑，M1-43）──
  const origFetch = globalThis.fetch.bind(globalThis);
  globalThis.fetch = function (
    input: RequestInfo | URL,
    init?: RequestInit
  ): Promise<Response> {
    let urlStr: string;
    try {
      urlStr =
        typeof input === 'string'
          ? input
          : input instanceof URL
            ? input.href
            : input.url;
    } catch {
      return origFetch(input, init);
    }
    if (!isTimedText(urlStr)) return origFetch(input, init);

    diagLog('interceptor', 'fetch timedtext request detected:', urlStr);
    const captured = origFetch(input, init);
    // 透傳原響應（不阻塞播放器）；另克隆 body 讀取以捕獲響應文本（§5.4：無持久監聽器）。
    void captured.then((res) => {
      diagLog('interceptor', 'fetch timedtext response received, status:', res.status);
      try {
        const clone = res.clone();
        void clone.text().then((text) => {
          diagLog('interceptor', 'fetch timedtext response body length:', text.length);
          emitCapture(
            urlStr,
            text,
            res.headers.get('content-type') ?? 'unknown',
            globalThis.location
          );
        });
      } catch {
        // §5.7：克隆/讀取失敗僅意味著本輪不複用，不影響播放器原請求。
      }
    });
    return captured;
  };
}

install();
