import type { AudioSourceHandle } from '../../../domain/models/audio';
import type { PlaybackState } from '../../../domain/models/playback';
import type { CaptionTrack, SubtitleSegment } from '../../../domain/models/subtitle';
import type { PlatformAdapter } from '../../../domain/ports/platform-adapter';
import { createLazyCaptionTrack, parseTimedText } from './timedtext';
import { diagLog } from '../../../infrastructure/debug-log';
import type { CapturedTrackInfo } from '../../../runtime/yt-timedtext-interceptor';

/**
 * YouTube 平台適配器——YouTube 改版風險的隔離點。
 * 所有 YouTube 專有邏輯（DOM 選擇器、字幕接口、播放器讀取）集中於此。
 */

const YT_WATCH_RE = /^https:\/\/(www\.)?youtube\.com\/watch\?/;

/** 字幕軌數據來源接口（封裝 player_response / timedtext URL）。 */
export interface CaptionSource {
  /** 返回字幕軌列表描述。 */
  fetchTrackList(): Promise<Array<{ lang: string; baseUrl: string; isAutoGenerated: boolean }>>;
  /** 拉取某軌內容並解析為內部段。 */
  fetchTracks(baseUrl: string, lang: string): Promise<SubtitleSegment[]>;
  /** 上次抓軌的診斷信息：供策略鏈在「無字幕軌」時區分「找不到數據源」vs「數據源無字幕」vs「解析失敗」。 */
  getLastTrackDiagnostic?(): string | undefined;
}

/**
 * 播放器 timedtext 響應複用來源（由 MAIN world 攔截器經消息橋提供）。
 * YouTube 2024+ 對 timedtext 加了 pot（proof-of-origin token）防護，content-script 直接
 * fetch 無 pot 的 baseUrl 只拿到空響應。播放器自身的 XHR 帶 pot 能成功——本接口讓
 * FetchCaptionSource 優先複用播放器已成功的響應，繞過 pot 生成。
 */
/** 捕獲響應的結構（供複用解析）。 */
export interface CapturedTimedText {
  url: string;
  responseText: string;
  contentType: string;
  /** 該捕獲所屬視頻 ID（從 timedtext URL `v` 提取）；用於跨視頻失效校驗。 */
  videoId?: string;
}

export interface CaptionCaptureProvider {
  /** 最近一次捕獲的 timedtext 響應；無捕獲時返回 null（回退到直接 fetch）。 */
  getLatest(): CapturedTimedText | null;
  /**
   * 等待捕獲值就緒（M1-43）。播放器的 timedtext 請求在「視頻已播放」時才發出，
   * fetchTracks 可能早於播放器請求運行——此時等待播放器發請求並捕獲。
   * 超時返回 null（由調用方回退直接 fetch）。
   * expectedVideoId（M1-45）：僅接受屬於該視頻的捕獲，避免複用上一個視頻的 stale 捕獲。
   */
  waitForCapture?(timeoutMs: number, expectedVideoId?: string): Promise<CapturedTimedText | null>;
  /**
   * M2-22 第三層：獲取 MAIN world 發現的軌道信息。
   * content script（isolated world）無法訪問 `movie_player.getOption()`，
   * 當 DOM stale 時使用這些信息作為 fallback。
   */
  getCapturedTracks?(expectedVideoId?: string): CapturedTrackInfo[];
  /**
   * M2-22 第四層：等待 MAIN world 發現的軌道信息。
   * 當 DOM stale 且 getCapturedTracks 返回空時，等待播放器發出 timedtext 請求並被攔截器發現。
   */
  waitForCapturedTracks?(timeoutMs: number, expectedVideoId: string): Promise<CapturedTrackInfo[]>;
}

/** 基於 fetch 的默認字幕數據源。 */
export class FetchCaptionSource implements CaptionSource {
  private readonly doc: Document;
  private readonly fetchFn: typeof fetch;
  private readonly captureProvider: CaptionCaptureProvider | undefined;
  /** 等待播放器捕獲響應的超時（毫秒）：視頻播放後播放器才發 timedtext 請求（M1-43）。 */
  private readonly waitForCaptureTimeoutMs: number;
  private lastTrackDiagnostic: string | undefined;

  /** 從當前文檔 URL 提取視頻 ID（`v` 參數）；非 watch 頁或解析失敗返回空串。 */
  private currentVideoId(): string {
    const href = this.doc.location?.href;
    if (!href) return '';
    try {
      return new URL(href).searchParams.get('v') ?? '';
    } catch {
      return '';
    }
  }

  constructor(
    doc: Document = globalThis.document,
    fetchFn: typeof fetch = globalThis.fetch,
    captureProvider?: CaptionCaptureProvider,
    waitForCaptureTimeoutMs: number = 15_000
  ) {
    this.doc = doc;
    // 綁定至 window：content-script 中直接調用未綁定的 window.fetch 會拋
    // "Illegal invocation"（fetch 需以 window 為接收者）。
    this.fetchFn = fetchFn === globalThis.fetch ? fetchFn.bind(globalThis) : fetchFn;
    this.captureProvider = captureProvider;
    this.waitForCaptureTimeoutMs = waitForCaptureTimeoutMs;
  }

  getLastTrackDiagnostic(): string | undefined {
    return this.lastTrackDiagnostic;
  }

  async fetchTrackList(): Promise<Array<{ lang: string; baseUrl: string; isAutoGenerated: boolean }>> {
    // R7：選擇器精確——優先取具名 #ytInitialPlayerResponse，避免 script:not([src])
    // 誤匹配頁面上任意內聯腳本（真實 YouTube 首個內聯 script 常非字幕數據）。
    diagLog('capture', 'fetchTrackList: starting, current URL:', this.doc.location?.href);
    const json = this.findPlayerResponseJson();
    if (!json) {
      // 找不到數據源：與「數據源無字幕」區分，供診斷鏈精確定位（§5.6 不靜默）。
      this.lastTrackDiagnostic = 'player response JSON not found (ytInitialPlayerResponse missing/empty)';
      diagLog('capture', 'fetchTrackList: player response JSON not found');
      return [];
    }
    // R7：外部 JSON 必須 try/catch 兜底，禁止 parse 錯誤冒泡成功能降級誤判。
    let data: {
      videoDetails?: { videoId?: string };
      captions?: { playerCaptionsTracklistRenderer?: { captionTracks?: Array<Record<string, unknown>> } };
    };
    try {
      data = JSON.parse(json);
    } catch (err) {
      // 解析失敗：記錄具體原因，不讓錯誤冒泡也不靜默。
      this.lastTrackDiagnostic = `player response JSON parse failed: ${err instanceof Error ? err.message : String(err)}`;
      diagLog('capture', 'fetchTrackList: JSON parse failed:', this.lastTrackDiagnostic);
      return [];
    }
    // M2-22：驗證 videoId——YouTube SPA 導航後 `ytInitialPlayerResponse` 不會更新，
    // 仍包含舊視頻的字幕數據。比對 player response 的 videoId 與當前 URL 的 v 參數，
    // 不匹配時視為 stale，嘗試從播放器元素 API 獲取當前視頻的字幕軌。
    const currentVid = this.currentVideoId();
    const playerVid = data.videoDetails?.videoId ?? '';
    // M2-22 補充：currentVid 為空（非 watch 頁）時直接返回空——無視頻可翻譯。
    if (!currentVid) {
      this.lastTrackDiagnostic = 'not on watch page (no videoId in URL)';
      diagLog('capture', 'fetchTrackList:', this.lastTrackDiagnostic);
      return [];
    }
    if (playerVid && currentVid !== playerVid) {
      this.lastTrackDiagnostic = `player response videoId mismatch: current=${currentVid}, player=${playerVid} (ytInitialPlayerResponse stale after SPA navigation)`;
      diagLog('capture', 'fetchTrackList:', this.lastTrackDiagnostic);
      const fallbackTracks = this.getCaptionTracksFromPlayer();
      if (fallbackTracks.length > 0) {
        diagLog('capture', 'fetchTrackList: fallback from player element succeeded, tracks:', fallbackTracks.length);
        return fallbackTracks;
      }
      // M2-22 第三層：content script 無法訪問播放器 API（isolated world 限制），
      // 嘗試使用 MAIN world 攔截器發現的軌道信息（通過 bridge postMessage 傳遞）。
      const capturedTracks = this.getCaptionTracksFromBridge(currentVid);
      if (capturedTracks.length > 0) {
        diagLog('capture', 'fetchTrackList: fallback from bridge captured tracks succeeded, tracks:', capturedTracks.length);
        return capturedTracks;
      }
      // M2-22 第四層：bridge 尚未收到軌道信息（攔截器發現 timedtext 請求需要時間）。
      // 等待播放器發出 timedtext 請求並被攔截器發現，超時才放棄。
      const waitedTracks = await this.waitForBridgeCapturedTracks(currentVid);
      if (waitedTracks.length > 0) {
        diagLog('capture', 'fetchTrackList: waitForBridgeCapturedTracks succeeded, tracks:', waitedTracks.length);
        return waitedTracks;
      }
      return [];
    }
    const tracks = data.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
    if (tracks.length === 0) {
      this.lastTrackDiagnostic = 'player response has no captionTracks (video may have no captions)';
      diagLog('capture', 'fetchTrackList: no captionTracks found');
    } else {
      this.lastTrackDiagnostic = undefined;
      diagLog('capture', 'fetchTrackList: found', tracks.length, 'tracks, first track baseUrl:', String(tracks[0].baseUrl ?? '').substring(0, 100));
    }
    return tracks.map((t) => ({
      lang: String(t.languageCode ?? 'und'),
      baseUrl: String(t.baseUrl ?? ''),
      isAutoGenerated: Boolean(t.kind === 'asr'),
    }));
  }

  /** 從頁面內嵌腳本提取 ytInitialPlayerResponse JSON 文本；找不到返回 undefined。 */
  private findPlayerResponseJson(): string | undefined {
    // 先取具名節點。
    const named = this.doc.querySelector('script#ytInitialPlayerResponse')?.textContent;
    if (named && named.trim()) {
      diagLog('capture', 'findPlayerResponseJson: found script#ytInitialPlayerResponse, length:', named.length);
      return named.trim();
    }
    // 回退：掃描內聯腳本，取形如 `var ytInitialPlayerResponse = {...};` 的賦值。
    const scripts = this.doc.querySelectorAll('script:not([src])');
    for (const el of Array.from(scripts)) {
      const text = el.textContent ?? '';
      const m = /ytInitialPlayerResponse\s*=\s*(\{[\s\S]*?\})\s*;/.exec(text);
      if (m) {
        diagLog('capture', 'findPlayerResponseJson: found ytInitialPlayerResponse assignment, length:', m[1].length);
        return m[1];
      }
      // 純 JSON 內聯（Mock 站點）：以 { 開頭且含 captions 關鍵字。
      const trimmed = text.trim();
      if (trimmed.startsWith('{') && trimmed.includes('captionTracks')) {
        diagLog('capture', 'findPlayerResponseJson: found inline JSON with captions, length:', trimmed.length);
        return trimmed;
      }
    }
    diagLog('capture', 'findPlayerResponseJson: ytInitialPlayerResponse not found in any script');
    return undefined;
  }

  /**
   * M2-22：當 `ytInitialPlayerResponse` stale（SPA 導航後未更新）時，
   * 從播放器元素 API `getOption('captions', 'tracklist')` 獲取當前視頻的字幕軌。
   * 播放器 API 在 SPA 導航後會更新為新視頻的數據，是可靠的 fallback。
   */
  private getCaptionTracksFromPlayer(): Array<{ lang: string; baseUrl: string; isAutoGenerated: boolean }> {
    const player = this.doc.getElementById('movie_player') as unknown as {
      getOption?: (m: string, k: string) => unknown;
    } | null;
    if (!player || typeof player.getOption !== 'function') {
      diagLog('capture', 'getCaptionTracksFromPlayer: player API not available');
      return [];
    }
    try {
      const raw = player.getOption('captions', 'tracklist');
      if (!Array.isArray(raw) || raw.length === 0) {
        diagLog('capture', 'getCaptionTracksFromPlayer: no tracks from player API');
        return [];
      }
      diagLog('capture', 'getCaptionTracksFromPlayer: got', raw.length, 'tracks from player API');
      return raw.map((t: Record<string, unknown>) => ({
        lang: String(t.languageCode ?? 'und'),
        baseUrl: String(t.baseUrl ?? ''),
        isAutoGenerated: Boolean(t.kind === 'asr'),
      }));
    } catch (err) {
      diagLog('capture', 'getCaptionTracksFromPlayer: error:', err instanceof Error ? err.message : String(err));
      return [];
    }
  }

  /**
   * M2-22 第三層：從 bridge 獲取 MAIN world 攔截器發現的軌道信息。
   * content script（isolated world）無法訪問 `movie_player.getOption()`，
   * 但 MAIN world 的攔截器可以。攔截器通過 postMessage 將軌道信息傳遞給 bridge，
   * 這裡從 bridge 讀取這些信息作為 fallback。
   */
  private getCaptionTracksFromBridge(videoId: string): Array<{ lang: string; baseUrl: string; isAutoGenerated: boolean }> {
    if (!this.captureProvider?.getCapturedTracks) {
      diagLog('capture', 'getCaptionTracksFromBridge: no getCapturedTracks provider');
      return [];
    }
    const tracks = this.captureProvider.getCapturedTracks(videoId);
    if (tracks.length === 0) {
      diagLog('capture', 'getCaptionTracksFromBridge: no captured tracks for videoId:', videoId);
      return [];
    }
    diagLog('capture', 'getCaptionTracksFromBridge: got', tracks.length, 'tracks from bridge');
    return tracks.map((t) => ({
      lang: t.lang,
      baseUrl: t.baseUrl,
      isAutoGenerated: t.isAutoGenerated,
    }));
  }

  /**
   * M2-22 第四層：等待 MAIN world 攔截器發現的軌道信息。
   * 當 bridge 尚未收到軌道信息時（攔截器發現 timedtext 請求需要時間），
   * 等待播放器發出請求並被攔截器發現，超時才放棄。
   */
  private async waitForBridgeCapturedTracks(videoId: string): Promise<Array<{ lang: string; baseUrl: string; isAutoGenerated: boolean }>> {
    if (!this.captureProvider?.waitForCapturedTracks) {
      diagLog('capture', 'waitForBridgeCapturedTracks: no waitForCapturedTracks provider');
      return [];
    }
    diagLog('capture', 'waitForBridgeCapturedTracks: waiting for tracks, videoId:', videoId);
    const tracks = await this.captureProvider.waitForCapturedTracks(this.waitForCaptureTimeoutMs, videoId);
    if (tracks.length === 0) {
      this.lastTrackDiagnostic = 'bridge waitForCapturedTracks timeout (no timedtext request captured in time)';
      diagLog('capture', 'waitForBridgeCapturedTracks: timeout, no tracks received');
      return [];
    }
    diagLog('capture', 'waitForBridgeCapturedTracks: got', tracks.length, 'tracks from bridge');
    return tracks.map((t) => ({
      lang: t.lang,
      baseUrl: t.baseUrl,
      isAutoGenerated: t.isAutoGenerated,
    }));
  }

  async fetchTracks(baseUrl: string, lang: string): Promise<SubtitleSegment[]> {
    diagLog('capture', 'fetchTracks called, baseUrl:', baseUrl.substring(0, 100), 'lang:', lang);
    // baseUrl 可能為相對路徑（Mock 站點），統一解析為絕對 URL。
    // §5.2/R2：new URL 可能因 baseUrl 非法而拋錯——拆出語義（URL 構造失敗）而非裸冒泡。
    let url: string;
    try {
      url = new URL(baseUrl, globalThis.location?.href ?? baseUrl).href;
    } catch (err) {
      throw new Error(
        `timedtext URL construct failed: ${err instanceof Error ? err.message : String(err)}`
      );
    }
    // 真實 YouTube 的 captionTracks[].baseUrl 不帶 fmt 時默認回 srv3 XML
    // （根為 <timedtext format="3">，子節點 body>p>s，非傳統 <transcript><text>），
    // 舊解析器會誤判「missing transcript root」或解析為空。強制 fmt=json3 取穩定 JSON
    // （{"events":[{tStartMs,dDurationMs,segs:[{utf8}]}]}），與解析器 JSON 分支對齊。
    // Mock 站點的相對 URL（無 host）不加 fmt，避免破壞既有契約。
    const finalUrl = this.withJson3Format(url);
    diagLog('capture', 'fetchTracks: finalUrl after withJson3Format:', finalUrl.substring(0, 100));

    // 優先複用 MAIN world 攔截器捕獲的播放器響應（帶 pot，已成功）。
    // §5.6：複用失敗（解析出錯）不靜默——記診斷後仍回退到直接 fetch，兩條路徑都留痕。
    diagLog('capture', 'fetchTracks: trying tryReuseCapture');
    const reused = this.tryReuseCapture(lang);
    if (reused) {
      diagLog('capture', 'fetchTracks: reused capture success, segments:', reused.length);
      return reused;
    }
    diagLog('capture', 'fetchTracks: no capture to reuse, trying waitForCaptureReuse');

    // M1-43：無捕獲值時，等待播放器發出 timedtext 請求並被攔截器捕獲。
    // 播放器在「視頻已播放」時才發字幕請求，而 fetchTracks 可能在播放前運行——
    // 給播放器一個窗口（waitForCaptureTimeoutMs）等待捕獲，命中則複用（繞過 pot），
    // 超時才回退直接 fetch（保留原有行為與診斷）。
    // M1-45：等待僅接受屬於當前視頻（expectedVideoId）的捕獲，避免換視頻後複用 stale 捕獲。
    const waited = await this.waitForCaptureReuse(lang);
    if (waited) {
      diagLog('capture', 'fetchTracks: waitForCaptureReuse success, segments:', waited.length);
      return waited;
    }
    diagLog('capture', 'fetchTracks: waitForCaptureReuse timeout, falling back to direct fetch');

    // §5.6：網絡層失敗（DNS/CORS/mixed-content/斷網）與 HTTP 非 2xx、body 解析失敗
    // 要**可區分**——統一記入 lastTrackDiagnostic 並攜帶實際證據（status/content-type/片段），
    // 避免「fetch 失敗」與「parse 失敗」混在同一條 run failed 裡無法定位。
    let res: Response;
    try {
      res = await this.fetchFn(finalUrl, { credentials: 'include' });
    } catch (err) {
      const msg = `timedtext fetch failed: ${err instanceof Error ? err.message : String(err)} (url: ${finalUrl})`;
      this.lastTrackDiagnostic = msg;
      diagLog('capture', 'fetchTracks: direct fetch failed:', msg);
      throw new Error(msg);
    }
    if (!res.ok) {
      const msg = `timedtext fetch HTTP ${res.status} (url: ${finalUrl})`;
      this.lastTrackDiagnostic = msg;
      diagLog('capture', 'fetchTracks: direct fetch HTTP error:', msg);
      throw new Error(msg);
    }
    let raw: string;
    try {
      raw = await res.text();
    } catch (err) {
      const msg = `timedtext body read failed: ${err instanceof Error ? err.message : String(err)}`;
      this.lastTrackDiagnostic = msg;
      diagLog('capture', 'fetchTracks: body read failed:', msg);
      throw new Error(msg);
    }
    try {
      const segments = parseTimedText(raw, lang);
      diagLog('capture', 'fetchTracks: direct fetch success, segments:', segments.length);
      return segments;
    } catch (err) {
      // §5.6：解析失敗（非法 JSON/XML/HTML 錯誤頁）記錄含響應證據的診斷，
      // 同時把 content-type 帶上（HTML 錯誤頁常為 text/html）。
      const msg = `${err instanceof Error ? err.message : String(err)} (content-type: ${
        res.headers.get('content-type') ?? 'unknown'
      })`;
      this.lastTrackDiagnostic = msg;
      diagLog('capture', 'fetchTracks: parse failed:', msg);
      throw new Error(msg);
    }
  }

  /** 為真實 YouTube timedtext URL 追加 fmt=json3（Mock 相對路徑不動）。 */
  private withJson3Format(url: string): string {
    try {
      const u = new URL(url);
      // 僅對 youtube 域名的 timedtext 追加，避免影響 Mock 站點的 /timedtext。
      if (u.hostname.endsWith('youtube.com') && u.pathname.includes('timedtext')) {
        u.searchParams.set('fmt', 'json3');
        return u.href;
      }
      return url;
    } catch (err) {
      // §5.2/P3：URL 構造失敗（url 本身非法）拋出語義明確的錯誤，不靜默回落原 url。
      throw new Error(
        `timedtext URL parse failed in withJson3Format: ${err instanceof Error ? err.message : String(err)}`
      );
    }
  }

  /**
    * 嘗試複用 MAIN world 攔截器捕獲的播放器 timedtext 響應。
    * - 有捕獲值、響應非空 → 解析；解析失敗記診斷並回退（返回 undefined 讓 fetch 兜底）。
    * - 無捕獲值 → 返回 undefined（走等待或直接 fetch）。
    * 
    * M2-22：恢復 videoId 驗證——攔截器的 `lastCapture` 在 MAIN world，
    * `bridge.clearLatest()` 只清空 isolated world 的緩存，MAIN world 的 `lastCapture`
    * 仍可能保留舊視頻的捕獲（重播機制會持續發送）。必須驗證捕獲的 videoId 與當前視頻匹配。
    */
   private tryReuseCapture(lang: string): SubtitleSegment[] | undefined {
     if (!this.captureProvider) {
       diagLog('capture', 'tryReuseCapture: no captureProvider');
       return undefined;
     }
     const capture = this.captureProvider.getLatest();
     if (!capture || !capture.responseText) {
       diagLog('capture', 'tryReuseCapture: no capture or empty responseText');
       return undefined;
     }
     // M2-22：驗證捕獲的 videoId 與當前視頻匹配，避免複用 SPA 導航後的 stale 捕獲。
     const currentVid = this.currentVideoId();
     if (currentVid && capture.videoId && currentVid !== capture.videoId) {
       diagLog('capture', 'tryReuseCapture: videoId mismatch, current:', currentVid, 'capture:', capture.videoId, '- skipping stale capture');
       return undefined;
     }
     diagLog('capture', 'tryReuseCapture: found capture, url:', capture.url.substring(0, 80), 'videoId:', capture.videoId);
    const { url, responseText, contentType } = capture;
    try {
      // 捕獲的響應可能為 srv3 XML（播放器請求無 fmt）或 json3（帶 fmt），
      // parseTimedText 自動按根識別，兩種都能解析。
      const segments = parseTimedText(responseText, lang);
      if (segments.length > 0) {
        this.lastTrackDiagnostic = `reused player timedtext capture (url: ${url})`;
        diagLog('capture', 'tryReuseCapture: parse success, segments:', segments.length);
        return segments;
      }
      // 捕獲值非空但解析出 0 段：可能不是字幕響應（如錯誤頁），記診斷並回退。
      this.lastTrackDiagnostic = `timedtext capture parse empty (content-type: ${contentType}, url: ${url})`;
      diagLog('capture', 'tryReuseCapture: parse empty, content-type:', contentType);
      return undefined;
    } catch (err) {
      // §5.6：捕獲響應解析失敗不靜默——記診斷（含 URL 證據），回退到直接 fetch。
      this.lastTrackDiagnostic =
        `timedtext capture parse failed: ${err instanceof Error ? err.message : String(err)}` +
        ` (content-type: ${contentType}, url: ${url})`;
      diagLog('capture', 'tryReuseCapture: parse failed:', this.lastTrackDiagnostic);
      return undefined;
    }
  }

  /**
    * 等待播放器捕獲響應後複用（M1-43）。
    * 僅當 provider 支持 waitForCapture 時等待；否則立即返回 undefined 走直接 fetch。
    * 
    * M2-22：傳入 expectedVideoId 確保只接受當前視頻的捕獲，避免 SPA 導航後複用 stale 捕獲。
    */
   private async waitForCaptureReuse(lang: string): Promise<SubtitleSegment[] | undefined> {
     if (!this.captureProvider?.waitForCapture) {
       diagLog('capture', 'waitForCaptureReuse: no waitForCapture provider');
       return undefined;
     }
     const expectedVideoId = this.currentVideoId();
     diagLog('capture', 'waitForCaptureReuse: waiting for capture, timeout:', this.waitForCaptureTimeoutMs, 'expectedVideoId:', expectedVideoId);
     let capture;
     try {
       capture = await this.captureProvider.waitForCapture(
         this.waitForCaptureTimeoutMs,
         expectedVideoId || undefined
       );
     } catch {
       // §5.6：等待過程異常不靜默——記診斷後回退直接 fetch。
       this.lastTrackDiagnostic = `timedtext capture wait failed`;
       diagLog('capture', 'waitForCaptureReuse: wait failed');
       return undefined;
     }
     if (!capture || !capture.responseText) {
       // §5.6：等待窗口內未捕獲到（播放器未發請求/請求未命中）不靜默——記診斷後回退直接 fetch，
       // 與「捕獲解析失敗」可區分。
       this.lastTrackDiagnostic = `timedtext capture wait timeout (${this.waitForCaptureTimeoutMs} ms) — fall back to direct fetch`;
       diagLog('capture', 'waitForCaptureReuse: timeout, no capture received');
       return undefined;
     }
     diagLog('capture', 'waitForCaptureReuse: capture received, url:', capture.url.substring(0, 80), 'videoId:', capture.videoId);
    // 用等待到的捕獲值直接解析（不依賴 getLatest——waitForCapture 的返回值即捕獲）。
    try {
      const segments = parseTimedText(capture.responseText, lang);
      if (segments.length > 0) {
        this.lastTrackDiagnostic = `reused player timedtext capture after wait (url: ${capture.url})`;
        diagLog('capture', 'waitForCaptureReuse: parse success, segments:', segments.length);
        return segments;
      }
      this.lastTrackDiagnostic = `timedtext capture parse empty (content-type: ${capture.contentType}, url: ${capture.url})`;
      diagLog('capture', 'waitForCaptureReuse: parse empty');
      return undefined;
    } catch (err) {
      this.lastTrackDiagnostic =
        `timedtext capture parse failed: ${err instanceof Error ? err.message : String(err)}` +
        ` (content-type: ${capture.contentType}, url: ${capture.url})`;
      diagLog('capture', 'waitForCaptureReuse: parse failed:', this.lastTrackDiagnostic);
      return undefined;
    }
  }
}

/** 可在任意播放器容器上工作的通用播放狀態監聽。 */
export class YouTubePlatformAdapter implements PlatformAdapter {
  readonly platformId = 'youtube';

  constructor(
    opts: {
      doc?: Document;
      videoSelector?: string;
      playerSelector?: string;
      captionSource?: CaptionSource;
      /** 覆蓋默認 YouTube 匹配規則（測試環境用於匹配 Mock 站點）。 */
      watchUrlRe?: RegExp;
    } = {}
  ) {
    this.doc = opts.doc ?? globalThis.document;
    this.videoSelector = opts.videoSelector ?? 'video.html5-main-video';
    this.playerSelector = opts.playerSelector ?? 'div#movie_player, .html5-video-player';
    this.captionSource = opts.captionSource ?? new FetchCaptionSource(this.doc);
    this.watchUrlRe = opts.watchUrlRe ?? YT_WATCH_RE;
  }

  private readonly doc: Document;
  private readonly videoSelector: string;
  private readonly playerSelector: string;
  private readonly captionSource: CaptionSource;
  private readonly watchUrlRe: RegExp;

  matches(url: string): boolean {
    return this.watchUrlRe.test(url);
  }

  observePlayback(cb: (state: PlaybackState) => void): () => void {
    const video = this.doc.querySelector<HTMLVideoElement>(this.videoSelector);
    if (!video) {
      // §5.6：播放器 <video> 缺失時不能靜默返回空訂閱——字幕時間對齊會無聲失效。
      // 此處無法發事件（observePlayback 僅回調），以日誌麵包屑留痕；
      // content-script/orchestrator 側另有顯式判空診斷兜底。
      console.warn(
        `[AI_Trans] observePlayback: video element not found (selector: ${this.videoSelector})`
      );
      return () => {};
    }

    const readState = (): PlaybackState => ({
      currentTime: Math.round(video.currentTime * 1000),
      playing: !video.paused && !video.ended,
      rate: video.playbackRate,
      duration: Math.round((video.duration || 0) * 1000),
      buffered: Array.from({ length: video.buffered.length }, (_, i) => ({
        start: Math.round(video.buffered.start(i) * 1000),
        end: Math.round(video.buffered.end(i) * 1000),
      })),
    });

    const handler = () => cb(readState());
    const events: Array<keyof HTMLMediaElementEventMap> = [
      'timeupdate',
      'play',
      'pause',
      'ratechange',
      'loadedmetadata',
      'progress',
      'seeked',
    ];
    for (const ev of events) video.addEventListener(ev, handler);
    handler();

    return () => {
      for (const ev of events) video.removeEventListener(ev, handler);
    };
  }

  async listCaptionTracks(): Promise<CaptionTrack[]> {
    const list = await this.captionSource.fetchTrackList();
    return list.map((t) =>
      createLazyCaptionTrack(t.lang, t.isAutoGenerated, () =>
        this.captionSource.fetchTracks(t.baseUrl, t.lang)
      )
    );
  }

  getLastTrackDiagnostic(): string | undefined {
    return this.captionSource.getLastTrackDiagnostic?.();
  }

  async getAudioSource(): Promise<AudioSourceHandle> {
    // M2 實現：tabCapture；M1 拋出以觸發降級。
    return {
      kind: 'tab-capture',
      start: async () => {
        throw new Error('tabCapture not implemented (M2)');
      },
      stop: async () => {},
    };
  }

  mountPoint(): HTMLElement {
    const player = this.doc.querySelector<HTMLElement>(this.playerSelector);
    if (!player) throw new Error('player mount point not found');
    return player;
  }
}

export type { SubtitleSegment };
