import type { AudioSourceHandle } from '../../../domain/models/audio';
import type { PlaybackState } from '../../../domain/models/playback';
import type { CaptionTrack, SubtitleSegment } from '../../../domain/models/subtitle';
import type { PlatformAdapter } from '../../../domain/ports/platform-adapter';
import { createLazyCaptionTrack, parseTimedText } from './timedtext';

/**
 * YouTube 平台適配器——YouTube 改版風險的隔離點。
 * 所有 YouTube 專有邏輯（DOM 選擇器、字幕接口、播放器讀取）集中於此。
 */

const YT_WATCH_RE = /^https:\/\/(www\.)?youtube\.com\/watch\?/;

/** 字幕軌數據來源接口（封裝 player_response / timedtext URL）。 */
export interface CaptionSource {
  /** 返回字幕軌列表描述。 */
  fetchTrackList(): Promise<Array<{ lang: string; baseUrl: string; isAutoGenerated: boolean }>>;
  /** 拉取某軌內容並解析為內部段。 */
  fetchTracks(baseUrl: string, lang: string): Promise<SubtitleSegment[]>;
  /** 上次抓軌的診斷信息：供策略鏈在「無字幕軌」時區分「找不到數據源」vs「數據源無字幕」vs「解析失敗」。 */
  getLastTrackDiagnostic?(): string | undefined;
}

/**
 * 播放器 timedtext 響應複用來源（由 MAIN world 攔截器經消息橋提供）。
 * YouTube 2024+ 對 timedtext 加了 pot（proof-of-origin token）防護，content-script 直接
 * fetch 無 pot 的 baseUrl 只拿到空響應。播放器自身的 XHR 帶 pot 能成功——本接口讓
 * FetchCaptionSource 優先複用播放器已成功的響應，繞過 pot 生成。
 */
export interface CaptionCaptureProvider {
  /** 最近一次捕獲的 timedtext 響應；無捕獲時返回 null（回退到直接 fetch）。 */
  getLatest(): { url: string; responseText: string; contentType: string } | null;
}

/** 基於 fetch 的默認字幕數據源。 */
export class FetchCaptionSource implements CaptionSource {
  private readonly doc: Document;
  private readonly fetchFn: typeof fetch;
  private readonly captureProvider: CaptionCaptureProvider | undefined;
  private lastTrackDiagnostic: string | undefined;

  constructor(
    doc: Document = globalThis.document,
    fetchFn: typeof fetch = globalThis.fetch,
    captureProvider?: CaptionCaptureProvider
  ) {
    this.doc = doc;
    // 綁定至 window：content-script 中直接調用未綁定的 window.fetch 會拋
    // "Illegal invocation"（fetch 需以 window 為接收者）。
    this.fetchFn = fetchFn === globalThis.fetch ? fetchFn.bind(globalThis) : fetchFn;
    this.captureProvider = captureProvider;
  }

  getLastTrackDiagnostic(): string | undefined {
    return this.lastTrackDiagnostic;
  }

  async fetchTrackList(): Promise<Array<{ lang: string; baseUrl: string; isAutoGenerated: boolean }>> {
    // R7：選擇器精確——優先取具名 #ytInitialPlayerResponse，避免 script:not([src])
    // 誤匹配頁面上任意內聯腳本（真實 YouTube 首個內聯 script 常非字幕數據）。
    const json = this.findPlayerResponseJson();
    if (!json) {
      // 找不到數據源：與「數據源無字幕」區分，供診斷鏈精確定位（§5.6 不靜默）。
      this.lastTrackDiagnostic = 'player response JSON not found (ytInitialPlayerResponse missing/empty)';
      return [];
    }
    // R7：外部 JSON 必須 try/catch 兜底，禁止 parse 錯誤冒泡成功能降級誤判。
    let data: {
      captions?: { playerCaptionsTracklistRenderer?: { captionTracks?: Array<Record<string, unknown>> } };
    };
    try {
      data = JSON.parse(json);
    } catch (err) {
      // 解析失敗：記錄具體原因，不讓錯誤冒泡也不靜默。
      this.lastTrackDiagnostic = `player response JSON parse failed: ${err instanceof Error ? err.message : String(err)}`;
      return [];
    }
    const tracks = data.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
    if (tracks.length === 0) {
      this.lastTrackDiagnostic = 'player response has no captionTracks (video may have no captions)';
    } else {
      this.lastTrackDiagnostic = undefined;
    }
    return tracks.map((t) => ({
      lang: String(t.languageCode ?? 'und'),
      baseUrl: String(t.baseUrl ?? ''),
      isAutoGenerated: Boolean(t.kind === 'asr'),
    }));
  }

  /** 從頁面內嵌腳本提取 ytInitialPlayerResponse JSON 文本；找不到返回 undefined。 */
  private findPlayerResponseJson(): string | undefined {
    // 先取具名節點。
    const named = this.doc.querySelector('script#ytInitialPlayerResponse')?.textContent;
    if (named && named.trim()) return named.trim();
    // 回退：掃描內聯腳本，取形如 `var ytInitialPlayerResponse = {...};` 的賦值。
    const scripts = this.doc.querySelectorAll('script:not([src])');
    for (const el of Array.from(scripts)) {
      const text = el.textContent ?? '';
      const m = /ytInitialPlayerResponse\s*=\s*(\{[\s\S]*?\})\s*;/.exec(text);
      if (m) return m[1];
      // 純 JSON 內聯（Mock 站點）：以 { 開頭且含 captions 關鍵字。
      const trimmed = text.trim();
      if (trimmed.startsWith('{') && trimmed.includes('captionTracks')) return trimmed;
    }
    return undefined;
  }

  async fetchTracks(baseUrl: string, lang: string): Promise<SubtitleSegment[]> {
    // baseUrl 可能為相對路徑（Mock 站點），統一解析為絕對 URL。
    // §5.2/R2：new URL 可能因 baseUrl 非法而拋錯——拆出語義（URL 構造失敗）而非裸冒泡。
    let url: string;
    try {
      url = new URL(baseUrl, globalThis.location?.href ?? baseUrl).href;
    } catch (err) {
      throw new Error(
        `timedtext URL construct failed: ${err instanceof Error ? err.message : String(err)}`
      );
    }
    // 真實 YouTube 的 captionTracks[].baseUrl 不帶 fmt 時默認回 srv3 XML
    // （根為 <timedtext format="3">，子節點 body>p>s，非傳統 <transcript><text>），
    // 舊解析器會誤判「missing transcript root」或解析為空。強制 fmt=json3 取穩定 JSON
    // （{"events":[{tStartMs,dDurationMs,segs:[{utf8}]}]}），與解析器 JSON 分支對齊。
    // Mock 站點的相對 URL（無 host）不加 fmt，避免破壞既有契約。
    const finalUrl = this.withJson3Format(url);

    // 優先複用 MAIN world 攔截器捕獲的播放器響應（帶 pot，已成功）。
    // §5.6：複用失敗（解析出錯）不靜默——記診斷後仍回退到直接 fetch，兩條路徑都留痕。
    const reused = this.tryReuseCapture(lang);
    if (reused) return reused;

    // §5.6：網絡層失敗（DNS/CORS/mixed-content/斷網）與 HTTP 非 2xx、body 解析失敗
    // 要**可區分**——統一記入 lastTrackDiagnostic 並攜帶實際證據（status/content-type/片段），
    // 避免「fetch 失敗」與「parse 失敗」混在同一條 run failed 裡無法定位。
    let res: Response;
    try {
      res = await this.fetchFn(finalUrl, { credentials: 'include' });
    } catch (err) {
      const msg = `timedtext fetch failed: ${err instanceof Error ? err.message : String(err)} (url: ${finalUrl})`;
      this.lastTrackDiagnostic = msg;
      throw new Error(msg);
    }
    if (!res.ok) {
      const msg = `timedtext fetch HTTP ${res.status} (url: ${finalUrl})`;
      this.lastTrackDiagnostic = msg;
      throw new Error(msg);
    }
    let raw: string;
    try {
      raw = await res.text();
    } catch (err) {
      const msg = `timedtext body read failed: ${err instanceof Error ? err.message : String(err)}`;
      this.lastTrackDiagnostic = msg;
      throw new Error(msg);
    }
    try {
      return parseTimedText(raw, lang);
    } catch (err) {
      // §5.6：解析失敗（非法 JSON/XML/HTML 錯誤頁）記錄含響應證據的診斷，
      // 同時把 content-type 帶上（HTML 錯誤頁常為 text/html）。
      const msg = `${err instanceof Error ? err.message : String(err)} (content-type: ${
        res.headers.get('content-type') ?? 'unknown'
      })`;
      this.lastTrackDiagnostic = msg;
      throw new Error(msg);
    }
  }

  /** 為真實 YouTube timedtext URL 追加 fmt=json3（Mock 相對路徑不動）。 */
  private withJson3Format(url: string): string {
    try {
      const u = new URL(url);
      // 僅對 youtube 域名的 timedtext 追加，避免影響 Mock 站點的 /timedtext。
      if (u.hostname.endsWith('youtube.com') && u.pathname.includes('timedtext')) {
        u.searchParams.set('fmt', 'json3');
        return u.href;
      }
      return url;
    } catch (err) {
      // §5.2/P3：URL 構造失敗（url 本身非法）拋出語義明確的錯誤，不靜默回落原 url。
      throw new Error(
        `timedtext URL parse failed in withJson3Format: ${err instanceof Error ? err.message : String(err)}`
      );
    }
  }

  /**
   * 嘗試複用 MAIN world 攔截器捕獲的播放器 timedtext 響應。
   * - 有捕獲值且響應非空 → 解析；解析失敗記診斷並回退（返回 undefined 讓 fetch 兜底）。
   * - 無捕獲值 → 返回 undefined（走直接 fetch）。
   */
  private tryReuseCapture(lang: string): SubtitleSegment[] | undefined {
    if (!this.captureProvider) return undefined;
    const capture = this.captureProvider.getLatest();
    if (!capture || !capture.responseText) return undefined;
    const { url, responseText, contentType } = capture;
    try {
      // 捕獲的響應可能為 srv3 XML（播放器請求無 fmt）或 json3（帶 fmt），
      // parseTimedText 自動按根識別，兩種都能解析。
      const segments = parseTimedText(responseText, lang);
      if (segments.length > 0) {
        this.lastTrackDiagnostic = `reused player timedtext capture (url: ${url})`;
        return segments;
      }
      // 捕獲值非空但解析出 0 段：可能不是字幕響應（如錯誤頁），記診斷並回退。
      this.lastTrackDiagnostic = `timedtext capture parse empty (content-type: ${contentType}, url: ${url})`;
      return undefined;
    } catch (err) {
      // §5.6：捕獲響應解析失敗不靜默——記診斷（含 URL 證據），回退到直接 fetch。
      this.lastTrackDiagnostic =
        `timedtext capture parse failed: ${err instanceof Error ? err.message : String(err)}` +
        ` (content-type: ${contentType}, url: ${url})`;
      return undefined;
    }
  }
}

/** 可在任意播放器容器上工作的通用播放狀態監聽。 */
export class YouTubePlatformAdapter implements PlatformAdapter {
  readonly platformId = 'youtube';

  constructor(
    opts: {
      doc?: Document;
      videoSelector?: string;
      playerSelector?: string;
      captionSource?: CaptionSource;
      /** 覆蓋默認 YouTube 匹配規則（測試環境用於匹配 Mock 站點）。 */
      watchUrlRe?: RegExp;
    } = {}
  ) {
    this.doc = opts.doc ?? globalThis.document;
    this.videoSelector = opts.videoSelector ?? 'video.html5-main-video';
    this.playerSelector = opts.playerSelector ?? 'div#movie_player, .html5-video-player';
    this.captionSource = opts.captionSource ?? new FetchCaptionSource(this.doc);
    this.watchUrlRe = opts.watchUrlRe ?? YT_WATCH_RE;
  }

  private readonly doc: Document;
  private readonly videoSelector: string;
  private readonly playerSelector: string;
  private readonly captionSource: CaptionSource;
  private readonly watchUrlRe: RegExp;

  matches(url: string): boolean {
    return this.watchUrlRe.test(url);
  }

  observePlayback(cb: (state: PlaybackState) => void): () => void {
    const video = this.doc.querySelector<HTMLVideoElement>(this.videoSelector);
    if (!video) {
      // §5.6：播放器 <video> 缺失時不能靜默返回空訂閱——字幕時間對齊會無聲失效。
      // 此處無法發事件（observePlayback 僅回調），以日誌麵包屑留痕；
      // content-script/orchestrator 側另有顯式判空診斷兜底。
      console.warn(
        `[AI_Trans] observePlayback: video element not found (selector: ${this.videoSelector})`
      );
      return () => {};
    }

    const readState = (): PlaybackState => ({
      currentTime: Math.round(video.currentTime * 1000),
      playing: !video.paused && !video.ended,
      rate: video.playbackRate,
      duration: Math.round((video.duration || 0) * 1000),
      buffered: Array.from({ length: video.buffered.length }, (_, i) => ({
        start: Math.round(video.buffered.start(i) * 1000),
        end: Math.round(video.buffered.end(i) * 1000),
      })),
    });

    const handler = () => cb(readState());
    const events: Array<keyof HTMLMediaElementEventMap> = [
      'timeupdate',
      'play',
      'pause',
      'ratechange',
      'loadedmetadata',
      'progress',
    ];
    for (const ev of events) video.addEventListener(ev, handler);
    handler();

    return () => {
      for (const ev of events) video.removeEventListener(ev, handler);
    };
  }

  async listCaptionTracks(): Promise<CaptionTrack[]> {
    const list = await this.captionSource.fetchTrackList();
    return list.map((t) =>
      createLazyCaptionTrack(t.lang, t.isAutoGenerated, () =>
        this.captionSource.fetchTracks(t.baseUrl, t.lang)
      )
    );
  }

  getLastTrackDiagnostic(): string | undefined {
    return this.captionSource.getLastTrackDiagnostic?.();
  }

  async getAudioSource(): Promise<AudioSourceHandle> {
    // M2 實現：tabCapture；M1 拋出以觸發降級。
    return {
      kind: 'tab-capture',
      start: async () => {
        throw new Error('tabCapture not implemented (M2)');
      },
      stop: async () => {},
    };
  }

  mountPoint(): HTMLElement {
    const player = this.doc.querySelector<HTMLElement>(this.playerSelector);
    if (!player) throw new Error('player mount point not found');
    return player;
  }
}

export type { SubtitleSegment };
