import type { AudioSourceHandle } from '../../../domain/models/audio';
import type { PlaybackState } from '../../../domain/models/playback';
import type { CaptionTrack, SubtitleSegment } from '../../../domain/models/subtitle';
import type { PlatformAdapter } from '../../../domain/ports/platform-adapter';
import { createLazyCaptionTrack, parseTimedText } from './timedtext';

/**
 * YouTube 平台適配器——YouTube 改版風險的隔離點。
 * 所有 YouTube 專有邏輯（DOM 選擇器、字幕接口、播放器讀取）集中於此。
 */

const YT_WATCH_RE = /^https:\/\/(www\.)?youtube\.com\/watch\?/;

/** 字幕軌數據來源接口（封裝 player_response / timedtext URL）。 */
export interface CaptionSource {
  /** 返回字幕軌列表描述。 */
  fetchTrackList(): Promise<Array<{ lang: string; baseUrl: string; isAutoGenerated: boolean }>>;
  /** 拉取某軌內容並解析為內部段。 */
  fetchTracks(baseUrl: string, lang: string): Promise<SubtitleSegment[]>;
}

/** 基於 fetch 的默認字幕數據源。 */
export class FetchCaptionSource implements CaptionSource {
  constructor(
    private readonly doc: Document = globalThis.document,
    private readonly fetchFn: typeof fetch = globalThis.fetch
  ) {}

  async fetchTrackList(): Promise<Array<{ lang: string; baseUrl: string; isAutoGenerated: boolean }>> {
    // 從頁面內嵌 ytInitialPlayerResponse 提取 captionTracks（含 timedtext baseUrl）。
    const json = this.doc
      .querySelector('script#ytInitialPlayerResponse, script:not([src])')
      ?.textContent;
    if (!json) return [];
    const data = JSON.parse(json) as {
      captions?: { playerCaptionsTracklistRenderer?: { captionTracks?: Array<Record<string, unknown>> } };
    };
    const tracks = data.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
    return tracks.map((t) => ({
      lang: String(t.languageCode ?? 'und'),
      baseUrl: String(t.baseUrl ?? ''),
      isAutoGenerated: Boolean(t.kind === 'asr'),
    }));
  }

  async fetchTracks(baseUrl: string, lang: string): Promise<SubtitleSegment[]> {
    const res = await this.fetchFn(baseUrl, { credentials: 'omit' });
    if (!res.ok) throw new Error(`timedtext fetch failed: ${res.status}`);
    const raw = await res.text();
    return parseTimedText(raw, lang);
  }
}

/** 可在任意播放器容器上工作的通用播放狀態監聽。 */
export class YouTubePlatformAdapter implements PlatformAdapter {
  readonly platformId = 'youtube';

  constructor(
    opts: {
      doc?: Document;
      videoSelector?: string;
      playerSelector?: string;
      captionSource?: CaptionSource;
    } = {}
  ) {
    this.doc = opts.doc ?? globalThis.document;
    this.videoSelector = opts.videoSelector ?? 'video.html5-main-video';
    this.playerSelector = opts.playerSelector ?? 'div#movie_player, .html5-video-player';
    this.captionSource = opts.captionSource ?? new FetchCaptionSource(this.doc);
  }

  private readonly doc: Document;
  private readonly videoSelector: string;
  private readonly playerSelector: string;
  private readonly captionSource: CaptionSource;

  matches(url: string): boolean {
    return YT_WATCH_RE.test(url);
  }

  observePlayback(cb: (state: PlaybackState) => void): () => void {
    const video = this.doc.querySelector<HTMLVideoElement>(this.videoSelector);
    if (!video) return () => {};

    const readState = (): PlaybackState => ({
      currentTime: Math.round(video.currentTime * 1000),
      playing: !video.paused && !video.ended,
      rate: video.playbackRate,
      duration: Math.round((video.duration || 0) * 1000),
      buffered: Array.from({ length: video.buffered.length }, (_, i) => ({
        start: Math.round(video.buffered.start(i) * 1000),
        end: Math.round(video.buffered.end(i) * 1000),
      })),
    });

    const handler = () => cb(readState());
    const events: Array<keyof HTMLMediaElementEventMap> = [
      'timeupdate',
      'play',
      'pause',
      'ratechange',
      'loadedmetadata',
      'progress',
    ];
    for (const ev of events) video.addEventListener(ev, handler);
    handler();

    return () => {
      for (const ev of events) video.removeEventListener(ev, handler);
    };
  }

  async listCaptionTracks(): Promise<CaptionTrack[]> {
    const list = await this.captionSource.fetchTrackList();
    return list.map((t) =>
      createLazyCaptionTrack(t.lang, t.isAutoGenerated, () =>
        this.captionSource.fetchTracks(t.baseUrl, t.lang)
      )
    );
  }

  async getAudioSource(): Promise<AudioSourceHandle> {
    // M2 實現：tabCapture；M1 拋出以觸發降級。
    return {
      kind: 'tab-capture',
      start: async () => {
        throw new Error('tabCapture not implemented (M2)');
      },
      stop: async () => {},
    };
  }

  mountPoint(): HTMLElement {
    const player = this.doc.querySelector<HTMLElement>(this.playerSelector);
    if (!player) throw new Error('player mount point not found');
    return player;
  }
}

export type { SubtitleSegment };
