// Mock YouTube 平臺適配器——集成測試用，可腳本化播放狀態與字幕軌。
import type { PlatformAdapter } from '../../src/domain/ports/platform-adapter';
import type { PlaybackState } from '../../src/domain/models/playback';
import type { CaptionTrack, SubtitleSegment } from '../../src/domain/models/subtitle';
import type { AudioSourceHandle, AudioChunk } from '../../src/domain/models/audio';

interface MockPlatformOpts {
  tracks?: CaptionTrack[];
  audioKind?: 'tab-capture' | 'buffered';
  /** 供 realtime-asr 策略消費的音頻分塊腳本。 */
  chunks?: AudioChunk[];
}

export class MockYouTubeAdapter implements PlatformAdapter {
  readonly platformId = 'youtube';
  private listeners = new Set<(s: PlaybackState) => void>();
  private tracks: CaptionTrack[];
  private audioKind: 'tab-capture' | 'buffered';
  readonly mount: HTMLElement;
  state: PlaybackState = {
    currentTime: 0,
    playing: true,
    rate: 1,
    duration: 600_000,
    buffered: [{ start: 0, end: 600_000 }],
  };

  constructor(opts: MockPlatformOpts = {}) {
    this.tracks = opts.tracks ?? [];
    this.audioKind = opts.audioKind ?? 'tab-capture';
    this.mount = document.createElement('div');
    this.mount.id = 'mock-player';
    document.body.appendChild(this.mount);
  }

  matches(url: string): boolean {
    return /youtube\.com\/watch/.test(url);
  }

  observePlayback(cb: (state: PlaybackState) => void): () => void {
    this.listeners.add(cb);
    cb(this.state);
    return () => this.listeners.delete(cb);
  }

  /** 測試驅動：推進播放狀態。 */
  emitPlayback(patch: Partial<PlaybackState>): void {
    this.state = { ...this.state, ...patch };
    for (const l of this.listeners) l(this.state);
  }

  setTracks(tracks: CaptionTrack[]): void {
    this.tracks = tracks;
  }

  async listCaptionTracks(): Promise<CaptionTrack[]> {
    return this.tracks;
  }

  async getAudioSource(): Promise<AudioSourceHandle> {
    return {
      kind: this.audioKind,
      start: async () => {},
      stop: async () => {},
    };
  }

  mountPoint(): HTMLElement {
    return this.mount;
  }
}

/** 便捷構造靜態原生字幕軌。 */
export function staticTrack(
  lang: string,
  segments: SubtitleSegment[],
  isAutoGenerated = false
): CaptionTrack {
  return { lang, isAutoGenerated, fetch: async () => segments };
}
