/**
 * 統一時間單位：毫秒，相對視頻起點。
 * domain 層所有時間軸使用該單位，由適配器負責換算。
 */
export type Millis = number;

/** 內部標準字幕段——所有字幕來源的統一輸出。 */
export interface SubtitleSegment {
  /** 穩定 ID，用於去重與更新。 */
  id: string;
  start: Millis;
  end: Millis;
  /** 原文（ASR 或原生字幕）。 */
  sourceText: string;
  /** 譯文（翻譯後回填）。 */
  translatedText?: string;
  /** BCP-47 語言碼，如 "en"、"zh-Hant"。 */
  sourceLang?: string;
  /** BCP-47 目標語言碼。 */
  targetLang?: string;
  /** 來源級別，便於觀測與降級決策。 */
  origin: CaptionOrigin;
  /** 是否為臨時（可被後續修正）字幕。 */
  provisional: boolean;
  /** provisional 修正版本號，遞增。 */
  revision: number;
}

export type CaptionOrigin = 'native' | 'lookahead-asr' | 'realtime-asr';

/** 平台字幕軌描述（原生字幕發現階段）。 */
export interface CaptionTrack {
  /** 軌語言（BCP-47）。 */
  lang: string;
  /** 顯示名。 */
  name?: string;
  /** 是否自動生成字幕。 */
  isAutoGenerated: boolean;
  /** 拉取並轉為內部結構。 */
  fetch(): Promise<SubtitleSegment[]>;
}
