import { describe, it, expect, vi } from 'vitest';
import { NativeCaptionStrategy } from '../../src/application/strategies/native-caption-strategy';
import type { StrategyContext } from '../../src/domain/ports/caption-strategy';
import type { PlatformAdapter } from '../../src/domain/ports/platform-adapter';
import type { TranslationProvider } from '../../src/domain/ports/translation-provider';
import type { CaptionTrack, SubtitleSegment } from '../../src/domain/models/subtitle';
import type { PipelineEvent } from '../../src/domain/models/events';

// 最小 mock platform：可控制 listCaptionTracks 行為。
function mockPlatform(behavior: 'tracks' | 'empty' | 'throw'): PlatformAdapter {
  const p = {
    platformId: 'youtube',
    listCaptionTracks: vi.fn(async (): Promise<CaptionTrack[]> => {
      if (behavior === 'empty') return [];
      if (behavior === 'throw') throw new Error('timedtext fetch failed: 404');
      const track: CaptionTrack = {
        lang: 'en',
        isAutoGenerated: false,
        fetch: async (): Promise<SubtitleSegment[]> => [
          {
            id: '0',
            start: 0,
            end: 2000,
            sourceText: 'hello',
            sourceLang: 'en',
            targetLang: undefined,
            origin: 'native',
            provisional: false,
            revision: 0,
          },
        ],
      };
      return [track];
    }),
  } as unknown as PlatformAdapter;
  return p;
}

function makeCtx(p: PlatformAdapter, diagnostics: string[]): StrategyContext {
  return {
    platform: p,
    playback: () => ({ currentTime: 0, playing: false, rate: 1, duration: 0, buffered: [] }),
    config: {
      translation: { type: 'local', model: 'm', endpoint: 'http://x/v1', fallbackType: 'mt' },
      asr: { type: 'local-whisper', modelTier: 'base' },
      targetLang: 'zh-Hant',
      displayMode: 'bilingual',
      performanceProfile: 'balanced',
    },
    asr: {
      engineId: 'noop',
      location: 'local' as const,
      warmup: async () => {},
      transcribe: async () => {
        throw new Error('not enabled');
      },
    },
    translation: {
      engineId: 'mt',
      location: 'local' as const,
      translate: async () => ({
        segments: [],
        targetLang: 'zh-Hant',
      }),
    } as TranslationProvider,
    diagnostics,
  };
}

describe('NativeCaptionStrategy 診斷可見性（§5.6）', () => {
  it('軌列表為空 → isApplicable=false 且診斷記錄「no caption tracks」', async () => {
    const diag: string[] = [];
    const s = new NativeCaptionStrategy();
    const ok = await s.isApplicable(makeCtx(mockPlatform('empty'), diag));
    expect(ok).toBe(false);
    expect(diag.some((d) => d.includes('native: no caption tracks found'))).toBe(true);
  });

  it('軌列表為空且平台提供診斷 → 原因包含平台診斷（找不到數據源 vs 無字幕）', async () => {
    const diag: string[] = [];
    const p = mockPlatform('empty') as unknown as PlatformAdapter & {
      getLastTrackDiagnostic: () => string;
    };
    p.getLastTrackDiagnostic = () => 'player response JSON not found (ytInitialPlayerResponse missing/empty)';
    const s = new NativeCaptionStrategy();
    await s.isApplicable(makeCtx(p, diag));
    expect(diag.some((d) => d.includes('player response JSON not found'))).toBe(true);
  });

  it('軌列表拋錯 → isApplicable=false 且診斷記錄異常詳情（不再靜默吞掉）', async () => {
    const diag: string[] = [];
    const s = new NativeCaptionStrategy();
    const ok = await s.isApplicable(makeCtx(mockPlatform('throw'), diag));
    expect(ok).toBe(false);
    expect(diag.some((d) => d.includes('native: listCaptionTracks failed') && d.includes('404'))).toBe(
      true
    );
  });

  it('有軌時 isApplicable=true，不污染診斷', async () => {
    const diag: string[] = [];
    const s = new NativeCaptionStrategy();
    const ok = await s.isApplicable(makeCtx(mockPlatform('tracks'), diag));
    expect(ok).toBe(true);
    expect(diag).toHaveLength(0);
  });

  it('run 全流程：抓軌→翻譯→emit segments-ready', async () => {
    const s = new NativeCaptionStrategy();
    const ctx = makeCtx(mockPlatform('tracks'), []);
    ctx.translation = {
      engineId: 'llm',
      location: 'local' as const,
      translate: async (input: { segments: SubtitleSegment[]; targetLang: string }) => ({
        segments: input.segments.map((seg) => ({ ...seg, translatedText: '你好', targetLang: 'zh-Hant' })),
        targetLang: 'zh-Hant',
      }),
    } as TranslationProvider;

    const events: PipelineEvent[] = [];
    await s.run(ctx, (e) => events.push(e));
    expect(events.some((e) => e.type === 'segments-ready')).toBe(true);
  });

  it('[M1-52] 引擎支持 translateStream 時走流式：首塊 segments-ready，後續 segments-updated', async () => {
    const s = new NativeCaptionStrategy();
    const ctx = makeCtx(mockPlatform('tracks'), []);
    ctx.translation = {
      engineId: 'llm',
      location: 'local' as const,
      translate: async () => ({ segments: [], targetLang: 'zh-Hant' }),
      // 模擬分塊漸進：連續 emit 兩次累計結果。
      translateStream: async (
        input: { segments: SubtitleSegment[]; targetLang: string },
        emit: (r: { segments: SubtitleSegment[]; engineId: string; degraded: boolean }) => void
      ) => {
        const first = input.segments.map((seg) => ({ ...seg, translatedText: '第一塊', targetLang: 'zh-Hant' }));
        emit({ segments: first, engineId: 'llm', degraded: false });
        const second = input.segments.map((seg) => ({ ...seg, translatedText: '第二塊', targetLang: 'zh-Hant' }));
        emit({ segments: second, engineId: 'llm', degraded: false });
      },
    } as TranslationProvider;

    const events: PipelineEvent[] = [];
    await s.run(ctx, (e) => events.push(e));

    const ready = events.filter((e) => e.type === 'segments-ready');
    const updated = events.filter((e) => e.type === 'segments-updated');
    expect(ready).toHaveLength(1);
    expect(updated).toHaveLength(1);
    // 首次為 ready（第一塊），後續為 updated（第二塊）。
    expect((ready[0] as { segments: SubtitleSegment[] }).segments[0].translatedText).toBe('第一塊');
    expect((updated[0] as { segments: SubtitleSegment[] }).segments[0].translatedText).toBe('第二塊');
  });

  it('[M1-52] 流式路徑 stop() 後不再 emit（訂閱清理 §5.4）', async () => {
    const s = new NativeCaptionStrategy();
    const ctx = makeCtx(mockPlatform('tracks'), []);
    ctx.translation = {
      engineId: 'llm',
      location: 'local' as const,
      translate: async () => ({ segments: [], targetLang: 'zh-Hant' }),
      translateStream: async (
        input: { segments: SubtitleSegment[]; targetLang: string },
        emit: (r: { segments: SubtitleSegment[]; engineId: string; degraded: boolean }) => void
      ) => {
        s.stop(); // 模擬翻譯途中被停止（SPA 導航/改配置 restart）。
        emit({ segments: input.segments, engineId: 'llm', degraded: false });
      },
    } as TranslationProvider;

    const events: PipelineEvent[] = [];
    await s.run(ctx, (e) => events.push(e));
    // stopped 後 emit 被忽略：無 segments-ready/updated。
    expect(events.some((e) => e.type === 'segments-ready' || e.type === 'segments-updated')).toBe(false);
  });
});
