import { describe, it, expect, vi } from 'vitest';
import { NativeCaptionStrategy } from '../../src/application/strategies/native-caption-strategy';
import type { StrategyContext } from '../../src/domain/ports/caption-strategy';
import type { PlatformAdapter } from '../../src/domain/ports/platform-adapter';
import type { TranslationProvider } from '../../src/domain/ports/translation-provider';
import type { CaptionTrack, SubtitleSegment } from '../../src/domain/models/subtitle';
import type { PipelineEvent } from '../../src/domain/models/events';

// 最小 mock platform：可控制 listCaptionTracks 行為。
function mockPlatform(behavior: 'tracks' | 'empty' | 'throw'): PlatformAdapter {
  const p = {
    platformId: 'youtube',
    listCaptionTracks: vi.fn(async (): Promise<CaptionTrack[]> => {
      if (behavior === 'empty') return [];
      if (behavior === 'throw') throw new Error('timedtext fetch failed: 404');
      const track: CaptionTrack = {
        lang: 'en',
        isAutoGenerated: false,
        fetch: async (): Promise<SubtitleSegment[]> => [
          {
            id: '0',
            start: 0,
            end: 2000,
            sourceText: 'hello',
            sourceLang: 'en',
            targetLang: undefined,
            origin: 'native',
            provisional: false,
            revision: 0,
          },
        ],
      };
      return [track];
    }),
  } as unknown as PlatformAdapter;
  return p;
}

function makeCtx(p: PlatformAdapter, diagnostics: string[]): StrategyContext {
  return {
    platform: p,
    playback: () => ({ currentTime: 0, playing: false, rate: 1, duration: 0, buffered: [] }),
    config: {
      translation: { type: 'local', model: 'm', endpoint: 'http://x/v1', fallbackType: 'mt' },
      asr: { type: 'local-whisper', modelTier: 'base' },
      targetLang: 'zh-Hant',
      displayMode: 'bilingual',
      performanceProfile: 'balanced',
    },
    asr: {
      engineId: 'noop',
      location: 'local' as const,
      warmup: async () => {},
      transcribe: async () => {
        throw new Error('not enabled');
      },
    },
    translation: {
      engineId: 'mt',
      location: 'local' as const,
      translate: async () => ({
        segments: [],
        targetLang: 'zh-Hant',
      }),
    } as TranslationProvider,
    diagnostics,
  };
}

describe('NativeCaptionStrategy 診斷可見性（§5.6）', () => {
  it('軌列表為空 → isApplicable=false 且診斷記錄「no caption tracks」', async () => {
    const diag: string[] = [];
    const s = new NativeCaptionStrategy();
    const ok = await s.isApplicable(makeCtx(mockPlatform('empty'), diag));
    expect(ok).toBe(false);
    expect(diag.some((d) => d.includes('native: no caption tracks found'))).toBe(true);
  });

  it('軌列表為空且平台提供診斷 → 原因包含平台診斷（找不到數據源 vs 無字幕）', async () => {
    const diag: string[] = [];
    const p = mockPlatform('empty') as unknown as PlatformAdapter & {
      getLastTrackDiagnostic: () => string;
    };
    p.getLastTrackDiagnostic = () => 'player response JSON not found (ytInitialPlayerResponse missing/empty)';
    const s = new NativeCaptionStrategy();
    await s.isApplicable(makeCtx(p, diag));
    expect(diag.some((d) => d.includes('player response JSON not found'))).toBe(true);
  });

  it('軌列表拋錯 → isApplicable=false 且診斷記錄異常詳情（不再靜默吞掉）', async () => {
    const diag: string[] = [];
    const s = new NativeCaptionStrategy();
    const ok = await s.isApplicable(makeCtx(mockPlatform('throw'), diag));
    expect(ok).toBe(false);
    expect(diag.some((d) => d.includes('native: listCaptionTracks failed') && d.includes('404'))).toBe(
      true
    );
  });

  it('有軌時 isApplicable=true，不污染診斷', async () => {
    const diag: string[] = [];
    const s = new NativeCaptionStrategy();
    const ok = await s.isApplicable(makeCtx(mockPlatform('tracks'), diag));
    expect(ok).toBe(true);
    expect(diag).toHaveLength(0);
  });

  it('run 全流程：抓軌→翻譯→emit segments-ready', async () => {
    const s = new NativeCaptionStrategy();
    const ctx = makeCtx(mockPlatform('tracks'), []);
    ctx.translation = {
      engineId: 'llm',
      location: 'local' as const,
      translate: async (input: { segments: SubtitleSegment[]; targetLang: string }) => ({
        segments: input.segments.map((seg) => ({ ...seg, translatedText: '你好', targetLang: 'zh-Hant' })),
        targetLang: 'zh-Hant',
      }),
    } as TranslationProvider;

    const events: PipelineEvent[] = [];
    await s.run(ctx, (e) => events.push(e));
    expect(events.some((e) => e.type === 'segments-ready')).toBe(true);
  });

  it('[M1-52] 引擎支持 translateStream 時走流式：首塊 segments-ready，後續 segments-updated', async () => {
    const s = new NativeCaptionStrategy();
    const ctx = makeCtx(mockPlatform('tracks'), []);
    ctx.translation = {
      engineId: 'llm',
      location: 'local' as const,
      translate: async () => ({ segments: [], targetLang: 'zh-Hant' }),
      // 模擬分塊漸進：連續 emit 兩次累計結果。
      translateStream: async (
        input: { segments: SubtitleSegment[]; targetLang: string },
        emit: (r: { segments: SubtitleSegment[]; engineId: string; degraded: boolean }) => void
      ) => {
        const first = input.segments.map((seg) => ({ ...seg, translatedText: '第一塊', targetLang: 'zh-Hant' }));
        emit({ segments: first, engineId: 'llm', degraded: false });
        const second = input.segments.map((seg) => ({ ...seg, translatedText: '第二塊', targetLang: 'zh-Hant' }));
        emit({ segments: second, engineId: 'llm', degraded: false });
      },
    } as TranslationProvider;

    const events: PipelineEvent[] = [];
    await s.run(ctx, (e) => events.push(e));

    const ready = events.filter((e) => e.type === 'segments-ready');
    const updated = events.filter((e) => e.type === 'segments-updated');
    expect(ready).toHaveLength(1);
    expect(updated).toHaveLength(1);
    // 首次為 ready（第一塊），後續為 updated（第二塊）。
    expect((ready[0] as { segments: SubtitleSegment[] }).segments[0].translatedText).toBe('第一塊');
    expect((updated[0] as { segments: SubtitleSegment[] }).segments[0].translatedText).toBe('第二塊');
  });

  it('[M1-52] 流式路徑 stop() 後不再 emit（訂閱清理 §5.4）', async () => {
    const s = new NativeCaptionStrategy();
    const ctx = makeCtx(mockPlatform('tracks'), []);
    ctx.translation = {
      engineId: 'llm',
      location: 'local' as const,
      translate: async () => ({ segments: [], targetLang: 'zh-Hant' }),
      translateStream: async (
        input: { segments: SubtitleSegment[]; targetLang: string },
        emit: (r: { segments: SubtitleSegment[]; engineId: string; degraded: boolean }) => void
      ) => {
        s.stop(); // 模擬翻譯途中被停止（SPA 導航/改配置 restart）。
        emit({ segments: input.segments, engineId: 'llm', degraded: false });
      },
    } as TranslationProvider;

    const events: PipelineEvent[] = [];
    await s.run(ctx, (e) => events.push(e));
    // stopped 後 emit 被忽略：無 segments-ready/updated。
    expect(events.some((e) => e.type === 'segments-ready' || e.type === 'segments-updated')).toBe(false);
  });
});

describe('NativeCaptionStrategy — Seek 響應與動態優先級', () => {
  // 構造多段 segments（10 段，每段 5s）供優先級測試。
  function multiSegmentTrack(): SubtitleSegment[] {
    return Array.from({ length: 10 }, (_, i) => ({
      id: String(i),
      start: i * 5000,
      end: (i + 1) * 5000,
      sourceText: `line-${i}`,
      sourceLang: 'en',
      targetLang: undefined,
      origin: 'native' as const,
      provisional: false,
      revision: 0,
    }));
  }

  function mockPlatformWithTrack(segments: SubtitleSegment[]): PlatformAdapter {
    return {
      platformId: 'youtube',
      listCaptionTracks: vi.fn(async (): Promise<CaptionTrack[]> => [
        { lang: 'en', isAutoGenerated: false, fetch: async () => segments },
      ]),
    } as unknown as PlatformAdapter;
  }

  function makeCtxWithPlayback(
    p: PlatformAdapter,
    currentTime: number
  ): StrategyContext {
    return {
      platform: p,
      playback: () => ({ currentTime, playing: true, rate: 1, duration: 60_000, buffered: [] }),
      config: {
        translation: { type: 'local', model: 'm', endpoint: 'http://x/v1', fallbackType: 'mt' },
        asr: { type: 'local-whisper', modelTier: 'base' },
        targetLang: 'zh-Hant',
        displayMode: 'bilingual',
        performanceProfile: 'balanced',
      },
      asr: {
        engineId: 'noop',
        location: 'local' as const,
        warmup: async () => {},
        transcribe: async () => { throw new Error('not enabled'); },
      },
      translation: {
        engineId: 'mt',
        location: 'local' as const,
        translate: async () => ({ segments: [], targetLang: 'zh-Hant' }),
      } as TranslationProvider,
      diagnostics: [],
    };
  }

  it('onSeek 設置 hasSeek 標記並中斷當前翻譯', async () => {
    const segments = multiSegmentTrack();
    const s = new NativeCaptionStrategy();
    const ctx = makeCtxWithPlayback(mockPlatformWithTrack(segments), 0);

    let aborted = false;
    ctx.translation = {
      engineId: 'llm',
      location: 'local' as const,
      translate: async () => ({ segments: [], targetLang: 'zh-Hant' }),
      translateStream: async (
        input: { segments: SubtitleSegment[]; targetLang: string; signal?: AbortSignal },
        emit: (r: { segments: SubtitleSegment[]; engineId: string; degraded: boolean }) => void
      ) => {
        // 檢查 signal 是否被 abort
        await new Promise<void>((resolve) => {
          if (input.signal?.aborted) { resolve(); return; }
          input.signal?.addEventListener('abort', () => { aborted = true; resolve(); }, { once: true });
          setTimeout(resolve, 2000);
        });
        if (input.signal?.aborted) {
          throw new DOMException('Aborted', 'AbortError');
        }
        emit({ segments: input.segments.map(seg => ({ ...seg, translatedText: 'translated' })), engineId: 'llm', degraded: false });
      },
    } as TranslationProvider;

    const events: PipelineEvent[] = [];
    const runPromise = s.run(ctx, (e) => events.push(e));

    // 等待 translateStream 開始並註冊 abort listener
    await new Promise((r) => setTimeout(r, 50));

    // 模擬 seek
    s.onSeek(30000);

    await runPromise;
    expect(aborted).toBe(true);
  });

  it('getPrioritizedSegments：滑動窗口 [currentTime+2s, currentTime+120s] 內的 segments 優先', () => {
    const segments = multiSegmentTrack();
    const s = new NativeCaptionStrategy();
    // 直接測試私有方法（通過 any 訪問）
    const getPrioritized = (s as unknown as { getPrioritizedSegments: (ct: number) => SubtitleSegment[] }).getPrioritizedSegments.bind(s);
    // 需要先設置 allSegments
    (s as unknown as { allSegments: SubtitleSegment[] }).allSegments = segments;

    // currentTime = 10000ms (10s)
    // 窗口：[12000, 130000]
    // 窗口內：segments 2-9 (start: 10000-45000) 中 start >= 12000 的 → segments 3-9 (start: 15000-45000)
    // 窗口外：segments 0-2 (start: 0-10000)
    const prioritized = getPrioritized(10000);
    // 窗口內的排前面
    expect(prioritized[0].start).toBeGreaterThanOrEqual(12000);
  });

  it('已翻譯的 segments 不會重複翻譯', () => {
    const segments = multiSegmentTrack();
    const s = new NativeCaptionStrategy();
    const translatedIds = (s as unknown as { translatedIds: Set<string> }).translatedIds;
    translatedIds.add('0');
    translatedIds.add('1');
    (s as unknown as { allSegments: SubtitleSegment[] }).allSegments = segments;

    const getPrioritized = (s as unknown as { getPrioritizedSegments: (ct: number) => SubtitleSegment[] }).getPrioritizedSegments.bind(s);
    const prioritized = getPrioritized(0);
    // 已翻譯的 0 和 1 不在結果中
    expect(prioritized.find(seg => seg.id === '0')).toBeUndefined();
    expect(prioritized.find(seg => seg.id === '1')).toBeUndefined();
    expect(prioritized.length).toBe(8);
  });

  it('mergeAccumulated：更新已存在的 segments，添加新的', () => {
    const s = new NativeCaptionStrategy();
    // 設置初始累計 segments
    (s as unknown as { accumulatedSegments: SubtitleSegment[] }).accumulatedSegments = [{
      id: '0', start: 0, end: 2000, sourceText: 'hello', translatedText: '舊翻譯',
      sourceLang: 'en', targetLang: 'zh-Hant', origin: 'native', provisional: false, revision: 0,
    }];

    const mergeAccumulated = (s as unknown as { mergeAccumulated: (segs: SubtitleSegment[]) => void }).mergeAccumulated.bind(s);
    mergeAccumulated([{
      id: '0', start: 0, end: 2000, sourceText: 'hello', translatedText: '新翻譯',
      sourceLang: 'en', targetLang: 'zh-Hant', origin: 'native', provisional: false, revision: 0,
    }, {
      id: '1', start: 2000, end: 4000, sourceText: 'world', translatedText: '新添加',
      sourceLang: 'en', targetLang: 'zh-Hant', origin: 'native', provisional: false, revision: 0,
    }]);

    // 讀取更新後的 accumulatedSegments
    const accumulated = (s as unknown as { accumulatedSegments: SubtitleSegment[] }).accumulatedSegments;
    expect(accumulated.length).toBe(2);
    expect(accumulated.find(s => s.id === '0')?.translatedText).toBe('新翻譯');
    expect(accumulated.find(s => s.id === '1')?.translatedText).toBe('新添加');
  });
});
